---
openapi: 3.0.3
info:
  title: CAS Row Sets
  contact:
    name: SAS Developers
    url: "https://developer.sas.com"
    email: devex@sas.com
  description: >
    ### Overview

    The CAS Row Sets REST API is used to retrieve row data from loaded CAS tables.  Edit
    operations are also supported.

    This documentation details endpoints specific to this API, as well as endpoints
    which extend the rowSets API spec.  As a result, the API can be exercised in two
    ways:

    1. Using the endpoints defined in this document directly.

    2. Using the rowSets API endpoints, where CAS Row Sets API acts as a provider.
    rowSets supports read-only operations on rows, and does not publicly expose edit
    capability.<p>

    ### Provider Implementation

    This CAS Row Sets API implements endpoints necessary to be classified as row sets
    provider for the Row Sets micro service.  The Row Sets micro service provides
    a standard REST API for referencing row data, independent of the underlying provider.<p><p>

    As a provider in this context, CAS Row Sets API supports the required endpoints
    defined in the Row Sets API documentation for reading row data.<p>

    #### HEAD Support

    Note that HEAD is supported for every GET request documented in the API. Simply
    change the HTTP verb from GET to HEAD, leaving other parameters the same. <p>

    #### Terminology Note

    When accessed via the provider endpoints, the term *source* is used to refer to
    a <i>location containing tables</i> and, for this provider, CAS tables.  A source
    in this context is typically a CAS library.<p>

    Within a CAS library, however, there is also the concept of a data *source*.  In
    this context, a source refers to the source table(s) accessible by a given CAS
    library.

    This is an important distinction to understand when using the Row Sets API, as
    the *CAS* Row Sets API sits between the Row Sets API and CAS, which both use the
    term *source*.
  version: "4"
servers:
- url: http://example.com/casRowSets
  description: This is an example base URL.
tags:
- name: Root
  description: Root paths.
- name: Rows
  description: Rows paths.
paths:
  /:
    get:
      operationId: root
      summary: API Root Resource
      description: API information
      tags:
      - Root
      responses:
        "200":
          description: Version information about the API.
    head:
      operationId: headersForRoot
      summary: Check availability
      description: >
        Returns whether or not the casRowSets service is running.

        This is identical to a GET request but will return only the HTTP headers with
        no document body.
      tags:
      - Root
      responses:
        "200":
          description: OK. Service is running and available
  "/servers/{serverName}/caslibs/{caslibName}/tables/{tableName}/rows":
    get:
      operationId: getRows
      summary: Get row data
      description: >
        Get row data from the table referenced.  Standard options for paging are
        supported, as well as support for sorting. Filtering is provided through
        use of the POST method on this same endpoint.
      tags:
      - Rows
      parameters:
      - name: serverName
        in: path
        description: |
          Server name containing the caslib and table being requested.
        required: true
        schema:
          type: string
      - name: caslibName
        in: path
        description: |
          The caslib name being requested.
        required: true
        schema:
          type: string
      - name: tableName
        in: path
        description: The name of the table being requested.
        required: true
        schema:
          type: string
      - name: start
        in: query
        description: The index of the first row in the result.
        schema:
          type: integer
          default: 0
      - name: limit
        in: query
        description: The maximum number of rows to return in this page of results.
          The actual number of returned rows may be less if the collection has been
          exhausted.
        schema:
          type: integer
          default: 10
      - name: format
        in: query
        description: Whether or not to format the cells of data.
        schema:
          type: boolean
          default: true
      - name: sortBy
        in: query
        description: >
          Sort returned rows of data. See [Sorting in REST
          APIs](https://developer.sas.com/rest-apis/casRowSets-v4/docs/getting-started/usage-notes#sorting)
          for more
          information on the format of the sort keys. <br> Rows by sorted by
          any valid column id. The default sort order will be ascending by row
          order (i.e. index). Some sample sorts: <ul> <li>Sort ascending by
          column with id COLUMN_A:
          /rowSets/tables/{tableName}/rows?sortBy=COLUMN_A:ascending</li>
          <li>Sort descending by column with id COLUMN_A:
          /rowSets/tables/{tableName}/rows?sortBy=COLUMN_A:descending</li>
          </ul> Only applicable for application/json and
          application/vnd.sas.collection+json response types.
        schema:
          type: string
          format: sort-criteria
      - name: formatted
        in: query
        description: Whether or not to apply sorting to formatted cells. Only applicable
          for application/json and application/vnd.sas.collection+json response types.
        schema:
          type: boolean
          default: false
      - name: includeIndex
        in: query
        description: Whether or not to include the row index as the first item in
          the row data. Only applicable for application/json and application/vnd.sas.collection+json
          response types.
        schema:
          type: boolean
          default: false
      - name: includeColumns
        in: query
        description: >
          Comma-separated list of columns for which to retrieve rows.  Cell
          data is returned in the order specified by this list.  When
          includeColumns is not specified, cell data is returned for all
          columns.  If a column name contains a comma, escape the comma by
          using two commas.  For example, the column name 'city,state' should
          be passed as 'city,,state'.
        schema:
          type: string
      - name: excludeItemLinks
        in: query
        description: Whether or not to exclude the links from this collection's items.
          Only applicable for application/json and application/vnd.sas.collection+json
          response types.
        schema:
          type: boolean
          default: true
      - name: sessionId
        in: query
        description: >
          The unique identifier of the session used to access the data service
          provider's backing service. When this is not specified the data
          service provider will create a temporary session, and then destroy
          it after the request is complete. If this is specified all returned
          links, except the "self" link, will have the sessionId query
          parameter added to there respective URIs. Also they will contain an
          additional session link to the application/vnd.sas.data.session
          resource that corresponds to the provided sessionId.
        schema:
          type: string
      - name: trailingWhitespaceMode
        in: query
        description: >
          Indicates how trailing whitespace will be handled.
          <p>Valid values include:
          <ul>
          <li>NONE - trailing whitespace is trimmed</li>
          <li>VARCHAR - trailing whitespace will be preserved in varchar columns</li>
          </ul>
          <p> Special considerations:
          <ul>
          <li>When initially uploading csv data, columns containing
          trailing whitespace must be double-quoted.</li>
          <li>The <i>format</i> option is not supported when preserving trailing
          whitespace, and will be ignored.</li>
          </ul>
        schema:
          type: string
          default: "NONE"
      responses:
        "200":
          description: OK
          content:
            application/vnd.sas.collection+json:
              schema:
                $ref: "#/components/schemas/rowCollection"
            application/json:
              schema:
                $ref: "#/components/schemas/rowCollection"
        "400":
          description: An invalid request was made
          content:
            application/vnd.sas.collection+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        "404":
          description: The table these rows are associated with does not exist
      x-sas-provider-contract: true
    post:
      operationId: getRowsFiltered
      summary: Get filtered row data
      description: >
        Get filtered row data from the table referenced.  Standard options for
        paging are supported, as well as support for sorting. Filtering is
        provided by providing the filter in the body of the request.
      tags:
      - Rows
      parameters:
      - name: serverName
        in: path
        description: |
          Server name containing the caslib and table being requested.
        required: true
        schema:
          type: string
      - name: caslibName
        in: path
        description: |
          The caslib name being requested.
        required: true
        schema:
          type: string
      - name: tableName
        in: path
        description: The name of the table being requested.
        required: true
        schema:
          type: string
      - name: start
        in: query
        description: The index of the first row in the result.
        schema:
          type: integer
          default: 0
      - name: limit
        in: query
        description: The maximum number of rows to return in this page of results.
          The actual number of returned rows may be less if the collection has been
          exhausted.
        schema:
          type: integer
          default: 10
      - name: format
        in: query
        description: Whether or not to format the cells of data.
        schema:
          type: boolean
          default: true
      - name: sortBy
        in: query
        description: >
          Sort returned rows of data. See [Sorting in REST
          APIs](https://developer.sas.com/rest-apis/casRowSets-v4/docs/getting-started/usage-notes#sorting)
          for more
          information on the format of the sort keys. <br> Rows by sorted by
          any valid column id. The default sort order will be ascending by row
          order (i.e. index). Some sample sorts: <ul> <li>Sort ascending by
          column with id COLUMN_A:
          /rowSets/tables/{tableName}/rows?sortBy=COLUMN_A:ascending</li>
          <li>Sort descending by column with id COLUMN_A:
          /rowSets/tables/{tableName}/rows?sortBy=COLUMN_A:descending</li>
          </ul>
        schema:
          type: string
          format: sort-criteria
      - name: formatted
        in: query
        description: Whether or not to apply sorting to formatted cells.
        schema:
          type: boolean
          default: false
      - name: includeIndex
        in: query
        description: Whether or not to include the row index as the first item in
          the row data.
        schema:
          type: boolean
          default: false
      - name: includeColumns
        in: query
        description: >
          Comma-separated list of columns for which to retrieve rows.  Cell
          data is returned in the order specified by this list.  When
          includeColumns is not specified, cell data is returned for all
          columns.  If a column name contains a comma, escape the comma by
          using two commas.  For example, the column name 'city,state' should
          be passed as 'city,,state'.
        schema:
          type: string
      - name: excludeItemLinks
        in: query
        description: Whether or not to exclude the links from this collection's items.
        schema:
          type: boolean
          default: true
      - name: sessionId
        in: query
        description: >
          The unique identifier of the session used to access the data service
          provider's backing service. When this is not specified the data
          service provider will create a temporary session, and then destroy
          it after the request is complete. If this is specified all returned
          links, except the "self" link, will have the sessionId query
          parameter added to there respective URIs. Also they will contain an
          additional session link to the application/vnd.sas.data.session
          resource that corresponds to the provided sessionId.
        schema:
          type: string
      requestBody:
        content:
          text/plain:
            schema:
              $ref: "#/components/schemas/where"
        description: The where clause to pass through to CAS. This acts as a filter
          on the provided data.
        required: true
      responses:
        "200":
          description: OK
          content:
            application/vnd.sas.collection+json:
              schema:
                $ref: "#/components/schemas/rowCollection"
            application/json:
              schema:
                $ref: "#/components/schemas/rowCollection"
        "400":
          description: |
            An invalid request was made
          content:
            application/vnd.sas.collection+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        "404":
          description: The table these rows are associated with does not exist
        "501":
          description: >
            One of the following query parameters is not supported by the
            provider service (parameter - errorCode): <ul> <li>sortBy - 12101
            </ul>
          content:
            application/vnd.sas.collection+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
  "/servers/{serverName}/caslibs/{caslibName}/tables/{tableName}/rows#add":
    post:
      operationId: addRows
      summary: Add rows
      description: >
        Adds additional rows to the referenced CAS table.  Since CAS row order is
        indeterminate,
        a specific insertion order is not supported.  Use sorted row retrieval to
        view ordered
        after they are added.  This operation is supported for loaded CAS tables only.
      tags:
      - Rows
      parameters:
      - name: serverName
        in: path
        description: |
          Server name containing the caslib and table being requested.
        required: true
        schema:
          type: string
      - name: caslibName
        in: path
        description: |
          The caslib name being requested.
        required: true
        schema:
          type: string
      - name: tableName
        in: path
        description: The name of the table being requested.
        required: true
        schema:
          type: string
      - name: sessionId
        in: query
        description: >
          The unique identifier of the session used to access the table.
          When not specified a temporary session will be created, and then destroyed
          after the request is complete. If this is specified all returned
          links, except the "self" link, will have the sessionId query
          parameter added to there respective URIs.
        schema:
          type: string
      requestBody:
        content:
          application/vnd.sas.cas.row.add.request+json:
            schema:
              $ref: "#/components/schemas/rowAddRequest"
            examples:
              json:
                $ref: "#/components/examples/rowAddRequest"
        description: Contains the column names whose values are to be set, as well
          as a list of one or more rows. Each row contains a sequence of cell values
          corresponding in order to the column names provided.
        required: true
      responses:
        "200":
          description: OK
          content:
            application/vnd.sas.cas.row.add.response+json:
              schema:
                $ref: "#/components/schemas/rowAddResponse"
              examples:
                one:
                  $ref: '#/components/examples/rowAddResponse'
        "400":
          description: |
            An invalid request was made
          content:
            application/vnd.sas.collection+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/errorResponse.json"
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/errorResponse.json"
        "404":
          description: The table does not exist.
        "409":
          description: |
            An error was returned from the CAS server.  The error is included in the response body.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                one:
                  $ref: '#/components/examples/errorResponse.json'
  "/servers/{serverName}/caslibs/{caslibName}/tables/{tableName}/rows#edit":
    post:
      operationId: editRows
      summary: Edit rows
      description: >
        Edit rows modifies the table cells for one or more rows matched by the where
        clause in the request body.
        Before performing the edit operation, it is recommended to validate the where
        clause by first using it to get and confirm the desired target rows.  This
        operation is supported for loaded CAS tables only.
      tags:
      - Rows
      parameters:
      - name: serverName
        in: path
        description: |
          Server name containing the caslib and table being requested.
        required: true
        schema:
          type: string
      - name: caslibName
        in: path
        description: |
          The caslib name being requested.
        required: true
        schema:
          type: string
      - name: tableName
        in: path
        description: The name of the table being requested.
        required: true
        schema:
          type: string
      - name: sessionId
        in: query
        description: >
          The unique identifier of the session used to access the table.
          When not specified a temporary session will be created, and then destroyed
          after the request is complete. If this is specified all returned
          links, except the "self" link, will have the sessionId query
          parameter added to there respective URIs.
        schema:
          type: string
      requestBody:
        content:
          application/vnd.sas.cas.row.edit.request+json:
            schema:
              $ref: "#/components/schemas/rowEditRequest"
            examples:
              json:
                $ref: "#/components/examples/rowEditRequest"
        description: Contains the where clause for row selection, and columns within
          those rows for which the edit operation should be performed.  The values
          specified will be set for all columns within the selected rows.
        required: true
      responses:
        "200":
          description: OK
          content:
            application/vnd.sas.cas.row.edit.response+json:
              schema:
                $ref: "#/components/schemas/rowEditResponse"
              examples:
                one:
                  $ref: '#/components/examples/rowEditResponse'
        "400":
          description: |
            An invalid request was made
          content:
            application/vnd.sas.collection+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/errorResponse.json"
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/errorResponse.json"
        "404":
          description: The table does not exist.
        "409":
          description: |
            An error was returned from the CAS server.  The error is included in the response body.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                one:
                  $ref: '#/components/examples/errorResponse.json'
  "/servers/{serverName}/caslibs/{caslibName}/tables/{tableName}/rows#delete":
    post:
      operationId: deleteRows
      summary: Delete rows
      description: >
        Delete rows removes the rows matched by the where clause provided in the request
        body.
        Before performing the delete operation, it is recommended to validate the
        where
        clause by first using it to get and confirm the desired target rows.  This
        operation is supported for loaded CAS tables only.
      tags:
      - Rows
      parameters:
      - name: serverName
        in: path
        description: |
          Server name containing the caslib and table being requested.
        required: true
        schema:
          type: string
      - name: caslibName
        in: path
        description: |
          The caslib name being requested.
        required: true
        schema:
          type: string
      - name: tableName
        in: path
        description: The name of the table being requested.
        required: true
        schema:
          type: string
      - name: sessionId
        in: query
        description: >
          The unique identifier of the session used to access the table.
          When not specified a temporary session will be created, and then destroyed
          after the request is complete. If this is specified all returned
          links, except the "self" link, will have the sessionId query
          parameter added to there respective URIs.
        schema:
          type: string
      requestBody:
        content:
          application/vnd.sas.cas.row.delete.request+json:
            schema:
              $ref: "#/components/schemas/rowDeleteRequest"
            examples:
              json:
                $ref: "#/components/examples/rowDeleteRequest"
        description: Contains the where clause for row selection, and columns within
          those rows for which the edit operation should be performed.  The values
          specified will be set for all columns within the selected rows.
        required: true
      responses:
        "200":
          description: OK
          content:
            application/vnd.sas.cas.row.delete.response+json:
              schema:
                $ref: "#/components/schemas/rowDeleteResponse"
              examples:
                one:
                  $ref: '#/components/examples/rowDeleteResponse'
        "400":
          description: |
            An invalid request was made
          content:
            application/vnd.sas.collection+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/errorResponse.json"
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/errorResponse.json"
        "404":
          description: The table does not exist.
        "409":
          description: |
            An error was returned from the CAS server.  The error is included in the response body.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                one:
                  $ref: '#/components/examples/errorResponse.json'
components:
  schemas:
    row:
      type: object
      description: Representation of a row summary object
      properties:
        cells:
          type: array
          description: >
            The cells for this row. Can be number, integer, null, boolean or
            string
          items:
            $ref: "#/components/schemas/cell"
        version:
          type: integer
          description: row schema version
        links:
          type: array
          description: Links that apply to this resource
          items:
            $ref: "#/components/schemas/link"
      example:
        version: 1
        cells:
        - 925
        - 850
        - CANADA
        - EAST
        - EDUCATION
        - FURNITURE
        - SOFA
        - 1
        - 1993
        - 12054
        links:
        - method: GET
          rel: up
          href: /casRowSets/servers/myCasServerName/caslibs/myCaslibName/tables/MYTABLENAME/rows
          uri: /casRowSets/servers/myCasServerName/caslibs/myCaslibName/tables/MYTABLENAME/rows
          type: application/vnd.sas.collection
          itemType: application/vnd.sas.data.row
    cell:
      description: >
        The cells for this row. Can be number, integer, null, boolean or
        string
    rowAddRequest:
      type: object
      description: Representation of a row add request object
      properties:
        version:
          type: integer
          description: schema version
        columns:
          type: array
          description: ordered list of column names to set for the new rows
          items:
            type: string
        rows:
          type: array
          description: list of rows to add
          items:
            type: array
            description: values to set for this row
            items:
              oneOf:
              - type: string
              - type: integer
    rowAddResponse:
      type: object
      description: Results of a successful add operation
      properties:
        version:
          type: integer
          description: schema version
        tableName:
          type: string
          description: Name of the table to which rows were added
        rowsAdded:
          type: integer
          description: The count of the number of added rows
        links:
          type: array
          description: Links that apply to this resource
          items:
            $ref: "#/components/schemas/link"
    rowEditRequest:
      type: object
      description: Representation of a row edit request object
      properties:
        version:
          type: integer
          description: schema version
        where:
          $ref: "#/components/schemas/where"
        values:
          type: object
          description: Map of string column names to the values to which the rows
            matching the where clause will be set.  Value types may vary.  An example
            request body is provided.
          additionalProperties: {}
    rowEditResponse:
      type: object
      description: Results of a successful edit operation
      properties:
        version:
          type: integer
          description: schema version
        tableName:
          type: string
          description: Name of the table for which the edit was performed
        rowsEdited:
          type: integer
          description: The count of the number of rows for which the edit was performed
        where:
          type: string
          description: |
            The row selection where clause which was used during the edit operation.
        links:
          type: array
          description: Links that apply to this resource
          items:
            $ref: "#/components/schemas/link"
    rowDeleteRequest:
      type: object
      description: Representation of a row delete request object
      properties:
        version:
          type: integer
          description: schema version
        where:
          $ref: "#/components/schemas/where"
    rowDeleteResponse:
      type: object
      description: Results of a successful delete operation
      properties:
        version:
          type: integer
          description: schema version
        tableName:
          type: string
          description: Name of the table for which the edit was performed
        rowsEdited:
          type: integer
          description: The count of the number of rows for which the edit was performed
        where:
          type: string
          description: |
            The row selection where clause which was used during the edit operation.
        links:
          type: array
          description: Links that apply to this resource
          items:
            $ref: "#/components/schemas/link"
    rowCollection:
      type: object
      description: A pageable collection of row resources
      properties:
        name:
          type: string
          description: The name of the collection "rows" in the context of the request.
        start:
          type: integer
          description: The 0-based index of the result candidates to start returning.
        limit:
          type: integer
          description: The maximum number of results requested.
        count:
          type: integer
          description: The actual number of results returned in the collection.
        accept:
          type: string
          description: A space-separated list of link types of the items in this collection.
        links:
          type: array
          description: Paging links that apply to this object
          items:
            $ref: "#/components/schemas/link"
        items:
          type: array
          description: The actual results of a query
          items:
            $ref: "#/components/schemas/row"
        version:
          type: integer
          description: Collection schema version
      example:
        name: rows
        accept: application/vnd.sas.data.row
        start: 0
        limit: 10
        items:
        - version: 1
          cells:
          - Antarctica
          - "1.0"
        - version: 1
          cells:
          - Puerto Rico
          - "2.0"
        - version: 1
          cells:
          - Virgin Islands (U.S.)
          - "3.0"
        - version: 1
          cells:
          - Aruba
          - "4.0"
        - version: 1
          cells:
          - Bahamas
          - "5.0"
        - version: 1
          cellCount: 2
          cells:
          - Bermuda
          - "6.0"
        - version: 1
          cells:
          - Belize
          - "7.0"
        - version: 1
          cells:
          - British Virgin Islands
          - "8.0"
        - version: 1
          cells:
          - Canada
          - "9.0"
        - version: 1
          cells:
          - Cayman Islands
          - "10.0"
        version: 2
        links:
        - method: GET
          rel: collection
          href: /casRowSets/servers/myCasServerName/caslibs/myCaslibName/tables/MYTABLENAME/rows
          uri: /casRowSets/servers/myCasServerName/caslibs/myCaslibName/tables/MYTABLENAME/rows
          type: application/vnd.sas.collection
          itemType: application/vnd.sas.data.row
        - method: GET
          rel: self
          href: /casRowSets/servers/myCasServerName/caslibs/myCaslibName/tables/MYTABLENAME/rows?start=0&limit=10
          uri: /casRowSets/servers/myCasServerName/caslibs/myCaslibName/tables/MYTABLENAME/rows?start=0&limit=10
          type: application/vnd.sas.collection
          itemType: application/vnd.sas.data.row
        - method: GET
          rel: up
          href: /casRowSets/servers/myCasServerName/caslibs/myCaslibName/tables/MYTABLENAME
          uri: /casRowSets/servers/myCasServerName/caslibs/myCaslibName/tables/MYTABLENAME
          type: application/vnd.sas.cas.table.details
    where:
      type: string
      description: >
        The where clause to pass through to the underlying data service. This
        acts as a filter on the provided data.
      example: ValueCol > 32000
    link:
      description: An object representing a link with at least relationship, method,
        and href properties
      required:
      - rel
      - method
      - href
      properties:
        rel:
          type: string
          description: |
            The link relation.
            A mnemonic string which indicates the meaning of
            this link. Use standard IANA link relations where appropriate.
            This is not a user-visible (UI) string.
        method:
          type: string
          description: |
            The HTTP method, one of GET, HEAD, PUT, POST, PATCH, DELETE.
        uri:
          type: string
          description: >
            The URI of the target resource, relative to the root of the API.
            Must

            start with /. One of uri or href is required
        href:
          type: string
          description: |
            The full URL. Must start with /.
        title:
          type: string
          description: |
            The human-readable title of this link.
        type:
          type: string
          description: |
            The primary link type. Required except for DELETE links.
        itemType:
          type: string
          description: >
            indicates what type or types will be used for collection items or
            composite types' nested object. This parallels the type member.
        responseType:
          type: string
          description: >
            Optional; indicates what types will be returned in the response body
            for

            PUT, POST, and PATCH methods.
        responseItemType:
          type: string
          description: >
            Optional; for PUT, POST, and PATCH methods, indicates what type or
            types will be used for collection items or for a composite types'
            nested objects. This parallels the responseType member.
    errorResponse:
      description: A standard error response object
      x-sas-media-type:
        name: vnd.sas.error
        version: 2
      properties:
        details:
          description: |
            Detailed information specific to this error; a list of strings. If
            appropriate, these strings should be localized as per the
            Accept-Language of the request.
          items:
            type: string
          type: array
        errorCode:
          description: |
            The system error code for reference (64-bit integer), often used for
            correlation with back-end service error message identifiers.
            Services should reserve a range in error code ranges and list
            specific error codes in error codes.
          format: int64
          type: integer
        httpStatusCode:
          description: |
            The HTTP status code error number (integer), 1xx, 2xx, 3xx, 4xx, or
            5xx values.
          type: integer
        links:
          description: |
            A list of com.sas.commons.rest.Link objects as per Link
            representation.
          items:
            $ref: "#/components/schemas/link"
          type: array
        message:
          description: |
            The back end system error message string. The message should be
            localized as per the Accept-Language of the request.
          type: string
        remediation:
          description: |
            Recommended actions to resolve the error; a list of strings. The
            remediation string should be localized as per the Accept-Language of
            the request.
          items:
            type: string
          type: array
        version:
          description: |
            Version information for this error format (integer, value 1).
          type: integer
      required:
      - version
      - errorCode
      - message
      title: Error response
  examples:

    rowAddRequest:
      summary: Row add request
      description: Sample of adding multiple rows.
      value:
        version: 1
        columns:
        - "CUSTNUM"
        - "CITY"
        - "STATE"
        - "ZIP"
        rows:
        - - 1
          - "CITY1"
          - "STATE1"
          - "00001"
        - - 2
          - "CITY2"
          - "STATE2"
          - "00002"

    rowAddResponse:
      summary: Added rows result
      description: Row add response indicates the result of the add operation.
      value:
        version: 1
        tableName: CUSTOMERS_UNWRANGLED_DATA
        rowsAdded: 2
        links:
        - method: POST
          rel: self
          href: "/casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATA/rows?sessionId=2927c609-91a7-2148-8c04-285a78c6d12f"
          uri: "/casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATA/rows?sessionId=2927c609-91a7-2148-8c04-285a78c6d12f"
          type: application/vnd.sas.cas.row.add.request
          responseType: application/vnd.sas.cas.row.add.response
        - method: POST
          rel: getRowsFiltered
          href: "/casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATA/rows?sessionId=2927c609-91a7-2148-8c04-285a78c6d12f"
          uri: "/casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATA/rows?sessionId=2927c609-91a7-2148-8c04-285a78c6d12f"
          type: text/plain
          responseType: application/vnd.sas.collection
    rowEditRequest:
      summary: Row edit request
      description: Sample of editing multiple cells for rows which match the where
        clause.
      value:
        version: 1
        where: "CITY='Washington'"
        values:
          STATE: 'DC'
          ZIP: '20017'
          CUSTNUM: 3590
    rowEditResponse:
      summary: Edited rows result
      description: Row edit response indicates the result of the edit operation.
      value:
        version: 1
        where: "CITY='Washington'"
        tableName: CUSTOMERS_UNWRANGLED_DATA
        rowsEdited: 9
        links:
        - method: POST
          rel: self
          href: "/casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATA/rows?sessionId=2927c609-91a7-2148-8c04-285a78c6d12f"
          uri: "/casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATA/rows?sessionId=2927c609-91a7-2148-8c04-285a78c6d12f"
          type: application/vnd.sas.cas.row.edit.request
          responseType: application/vnd.sas.cas.row.edit.response
        - method: POST
          rel: getRowsFiltered
          href: "/casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATA/rows?sessionId=2927c609-91a7-2148-8c04-285a78c6d12f"
          uri: "/casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATA/rows?sessionId=2927c609-91a7-2148-8c04-285a78c6d12f"
          type: text/plain
          responseType: application/vnd.sas.collection
    rowDeleteRequest:
      summary: Row delete request
      description: Sample of deleting multiple rows which match the where clause.
      value:
        version: 1
        where: "CITY='Washington'"
    rowDeleteResponse:
      summary: Deleted rows result
      description: Row delete response indicates the result of the delete operation.
      value:
        version: 1
        where: "CITY='Washington'"
        tableName: CUSTOMERS_UNWRANGLED_DATA
        rowsDeleted: 9
        links:
        - method: POST
          rel: self
          href: "/casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATA/rows?sessionId=2927c609-91a7-2148-8c04-285a78c6d12f"
          uri: "/casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATA/rows?sessionId=2927c609-91a7-2148-8c04-285a78c6d12f"
          type: application/vnd.sas.cas.row.delete.request
          responseType: application/vnd.sas.cas.row.delete.response
        - method: POST
          rel: getRowsFiltered
          href: "/casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATA/rows?sessionId=2927c609-91a7-2148-8c04-285a78c6d12f"
          uri: "/casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATA/rows?sessionId=2927c609-91a7-2148-8c04-285a78c6d12f"
          type: text/plain
          responseType: application/vnd.sas.collection
    errorResponse.json:
      summary: Error response example
      description: Example error response for table could not be loaded.
      x-sas-media-type:
        name: vnd.sas.error
        version: 2
      value: |
        {
          "version": 2,
          "httpStatusCode": 404,
          "errorCode": 12206,
          "message": "A table could not be loaded.",
          "details": [
            "2-0-2720327: 0x88bfc147:TKCASA_GEN_TABLE_NOT_LOADED",
            "ERROR: A table could not be loaded.",
            "ERROR: The action stopped due to errors.",
            "path: /casRowSets/servers/cas-shared-default/caslibs/Public/tables/CUSTOMERS_UNWRANGLED_DATAx/rows",
            "correlator: aa1ee09b-c9e6-4909-aa38-bd98dc9c27a7"
          ]
        }
