---
openapi: 3.0.3
info:
  title: Detection Transaction
  description: |
    This API provides an entry point for SDA TAS
  version: '1'
  contact:
    name: SAS Developers
    url: 'https://developer.sas.com'
    email: devex@sas.com
  termsOfService: 'https://www.sas.com/en_us/legal/copyright.html'
servers:
- url: 'http://mock-detection.apifirst.unx.sas.com/detectionTransaction'
  description: kubernetes mock server
tags:
- name: Root
  description: The operations for the root resource.
paths:
  /:
    get:
      tags:
      - Root
      summary: Get a list of top-level links
      operationId: root
      description: Returns a list of links to the top-level resources surfaced through
        this API.
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              description: Always "application/vnd.sas.api+json".
              schema:
                type: string
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: '#/components/schemas/apiList'
              examples:
                example-1:
                  value:
                    version: 1
                    links:
                    - ref: self
                      method: GET
                      type: application/vnd.sas.api
                      uri: /detectionTransaction
                      href: /detectionTransaction
            application/json:
              schema:
                $ref: '#/components/schemas/apiList'
        '404':
          $ref: '#/components/responses/errorInRequest'
components:
  responses:
    errorInRequest:
      description: 'There was an error in the request. If the query parameter of debug
        is set to true, then the body is as follows. If not, then the body is the
        returned ION that contains an SMH variable set with the error information.'
      headers:
        Content-Type:
          description: Usually application/vnd.sas.error
          schema:
            type: string
        Location:
          description: Provided if a location would be meaningful in the error context.
          schema:
            type: string
        Last-Modified:
          description: Provided only if meaningful in the error context.
          schema:
            type: string
        X-App-Status:
          schema:
            type: string
          description: Where an error exists in the provided ION
      content:
        application/vnd.sas.error:
          schema:
            $ref: '#/components/schemas/error2'
        application/json:
          schema:
            $ref: '#/components/schemas/error2'
  schemas:
    apiList:
      type: object
      description: The standard object for the top level resource of the service.  Contains
        a list of link objects.
      x-sas-media-type:
        name: application/vnd.sas.api
        version: 1
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
          minimum: 1
        links:
          description: The API's top-level links.
          type: array
          items:
            $ref: '#/components/schemas/link'
      example:
        version: 1
        links:
        - ref: self
          method: GET
          type: application/vnd.sas.api
          uri: /detectionTransaction
          href: /detectionTransaction
    link:
      type: object
      description: A standard link relationship present on most responses in json
        or xml format
      properties:
        method:
          type: string
          description: the HTTP method to invoke this endpoint
        rel:
          type: string
          description: The relationship of this URL to the object
        uri:
          type: string
          description: The relative URI of the REST endpoint
        href:
          type: string
          description: The full URL of the REST endpoint
        type:
          type: string
          description: The media type to specify in the accept/content-type header
            for this request
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT
            `POST or `PATCH` operation
        responseItemType:
          type: string
          description: 'The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation'
      example:
        method: GET
        rel: self
        uri: 'http://example.com/detectionTransaction'
        href: 'http://example.com/detectionTransaction'
        type: application/vnd.sas.collection
        responseItemType: application/json
    error2:
      type: object
      description: Standard media type for error response.
      x-sas-media-type:
        name: application/vnd.sas.error
        version: 2
      properties:
        message:
          type: string
          description: The message for the error.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred.
          items:
            $ref: '#/components/schemas/error2'
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: '#/components/schemas/link'
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
  examples: {}
