---
openapi: 3.0.3
info:
  title: Fabric Decision Builder Adapter
  contact:
    name: SAS Developers
    url: https://developer.sas.com
    email: devex@sas.com
  description: The Fabric Decision Builder Adapter provides an implementation of the
    Microsoft Fabric Workload and Job APIs.
  version: "1"
servers:
- url: "https://example.com/fabricDecisionBuilderAdapter"
  description: "This is an example of a base URL."
tags:
- name: Root
  description: Contains the operation for the root resource.
- name: EndpointResolution
  description: Contains the operation for endpoint resolution.
- name: AdminOperation
  description: Contains the CRUD operations for Microsoft Fabric tenant to SAS Viya
    mapping.
paths:
  /:
    get:
      tags:
      - Root
      summary: Respond to a ping
      description: Respond to a ping request to show that this API is reachable.
      operationId: root
      responses:
        "200":
          description: This API is reachable.
          content:
            text/plain:
              example: OK
        "500":
          description: An error occurred when replying to the ping.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/operationError"
              example:
                $ref: "#/components/examples/operationError"
  /entries:
    post:
      tags:
      - AdminOperation
      summary: Update mapping
      description: Update the Microsoft Fabric tenant to SAS Viya deployment mapping.
      operationId: createMapping
      parameters:
      - name: Authorization
        in: header
        description: Supply a bearer token
        required: true
        schema:
          type: string
        example: Bearer token
      requestBody:
        $ref: "#/components/requestBodies/recordMappingRequest"
      responses:
        "201":
          description: The operation is successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/newMappingResponse"
              example:
                $ref: "#/components/examples/newMappingResponse"
        "400":
          description: A user error occurred.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/userError"
              example:
                $ref: "#/components/examples/userError"
        "403":
          description: The authorization token is invalid.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/userError"
              example:
                $ref: "#/components/examples/userError"
        "500":
          description: A system error occurred.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/operationError"
              example:
                $ref: "#/components/examples/operationError"
  /entries/{tenantId}:
    get:
      tags:
      - AdminOperation
      summary: Retrieve mapping
      description: Retrieve the Microsoft Fabric tenant to SAS Viya deployment mapping.
      operationId: getMapping
      parameters:
      - name: tenantId
        in: path
        description: Identifier of a Microsoft Fabric tenant.
        required: true
        schema:
          type: string
        example: 6e74ccf1-bc11-46a4-96d3-38a7cda7e37e
      - name: Authorization
        in: header
        description: Supply a bearer token
        required: true
        schema:
          type: string
        example: Bearer token
      responses:
        "200":
          description: The operation is successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/mappingResponse"
              example:
                $ref: "#/components/examples/mappingResponse"
        "400":
          description: A user error occurred.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/userError"
              example:
                $ref: "#/components/examples/userError"
        "403":
          description: The authorization token is invalid.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/userError"
              example:
                $ref: "#/components/examples/userError"
        "500":
          description: A system error occurred.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/operationError"
              example:
                $ref: "#/components/examples/operationError"
    put:
      tags:
      - AdminOperation
      summary: Update mapping
      description: Update a previously recorded Microsoft Fabric tenant to SAS Viya
        deployment mapping. Conditional update is not provided because this is an
        operation for a single privileged user.
      operationId: updateMapping
      parameters:
      - name: tenantId
        in: path
        description: Identifier of a Microsoft Fabric tenant.
        required: true
        schema:
          type: string
        example: 6e74ccf1-bc11-46a4-96d3-38a7cda7e37e
      - name: Authorization
        in: header
        description: Supply a bearer token
        required: true
        schema:
          type: string
        example: Bearer token
      requestBody:
        $ref: "#/components/requestBodies/recordMappingRequest"
      responses:
        "200":
          description: The operation is successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/newMappingResponse"
              example:
                $ref: "#/components/examples/newMappingResponse"
        "400":
          description: A user error occurred.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/userError"
              example:
                $ref: "#/components/examples/userError"
        "403":
          description: The authorization token is invalid.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/userError"
              example:
                $ref: "#/components/examples/userError"
        "500":
          description: A system error occurred.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/operationError"
              example:
                $ref: "#/components/examples/operationError"
    delete:
      tags:
      - AdminOperation
      summary: Delete mapping
      description: Delete the Microsoft Fabric tenant to SAS Viya deployment mapping.
      operationId: deleteMapping
      parameters:
      - name: tenantId
        in: path
        description: Identifier of a Microsoft Fabric tenant.
        required: true
        schema:
          type: string
        example: 6e74ccf1-bc11-46a4-96d3-38a7cda7e37e
      - name: Authorization
        in: header
        description: Supply a bearer token
        required: true
        schema:
          type: string
        example: Bearer token
      responses:
        "204":
          description: The operation is successful.
        "400":
          description: A user error occurred.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/userError"
              example:
                $ref: "#/components/examples/userError"
        "403":
          description: The authorization token is invalid.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/userError"
              example:
                $ref: "#/components/examples/userError"
        "500":
          description: A system error occurred.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/operationError"
              example:
                $ref: "#/components/examples/operationError"
  /resolutions:
    post:
      tags:
      - EndpointResolution
      summary: Resolve the endpoint that Microsoft Fabric should use to carry out
        an operation
      description: Resolve the endpoint that Microsoft Fabric should use to carry
        out an operation of the Item Lifecycle and Job APIs. This endpoint fulfills
        https://learn.microsoft.com/en-us/rest/api/fabric/workload/workloadapi/endpoint-resolution/resolve.
      operationId: createResolution
      parameters:
      - name: Authorization
        in: header
        description: This header follows this format - SubjectAndAppToken1.0 subjectToken="delegated
          token", appToken="S2S token".
        required: true
        schema:
          type: string
        example: SubjectAndAppToken1.0 subjectToken="JWT token", appToken="JWT token"
      requestBody:
        $ref: "#/components/requestBodies/resolutionRequest"
      responses:
        "200":
          description: The resolution is successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/resolutionResponse"
              example:
                $ref: "#/components/examples/resolutionResponse"
        "403":
          description: The authorization token is invalid.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/userError"
              example:
                $ref: "#/components/examples/userError"
        "500":
          description: An error occurred in the process of resolving the endpoint.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              example:
                $ref: "#/components/examples/errorResponse"
components:
  requestBodies:
    recordMappingRequest:
      description: The payload for recording a Microsoft Fabric tenant to SAS Viya
        deployment.
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/recordMappingRequest"
          example:
            $ref: "#/components/examples/recordMappingRequest"
    resolutionRequest:
      description: The resolution request payload.
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/resolutionRequest"
          example:
            $ref: "#/components/examples/resolutionRequest"
  schemas:
    errorAdditionalInformation:
      title: Additional error information
      description: Information of an error.
      properties:
        message:
          type: string
        errorCode:
          type: string
    errorResponse:
      title: Error response
      description: The information about an error returned to Microsoft Fabric.
      properties:
        message:
          type: string
        errorCode:
          type: string
        isPermanent:
          type: boolean
        source:
          type: string
          enum:
          - System
          - User
          - External
        moreDetails:
          type: array
          description: Additional information about the error.
          items:
            $ref: "#/components/schemas/errorAdditionalInformation"
    mappingResponse:
      title: Mapping response
      description: The response for a mapping retrieval request.
      properties:
        tenantId:
          type: string
          description: The identifier of a Microsoft Fabric tenant.
        region:
          type: string
          description: The geographical region of a Microsoft Fabric tenant.
        url:
          type: string
          description: The base URL of a Viya deployment.
    newMappingResponse:
      title: New mapping response
      description: The response for a new mapping request.
      properties:
        id:
          type: string
          description: The identifier of the mapping.
    operationError:
      title: Operation Error
      description: The error interface for operation error.
      properties:
        message:
          type: string
          description: The error message.
    recordMappingRequest:
      title: Record mapping request
      description: The request body for mapping a Microsoft Fabric tenant ID to a
        SAS Viya deployment.
      properties:
        tenantId:
          type: string
          description: The identifier of a Microsoft Fabric tenant.
        tenantRegion:
          type: string
          description: The geographical region of a Microsoft Fabric tenant.
        viyaUrl:
          type: string
          description: The base URL of a Viya deployment.
    resolutionContextProperty:
      title: Resolution Context Properties
      description: The strategy to employ to resolve an endpont.
      properties:
        name:
          type: number
          description: The numeric value that identifies a resolution strategy. Microsoft
            Fabric documentation says this should be a string value. However, in reality
            a number is sent. See https://learn.microsoft.com/en-us/rest/api/fabric/workload/workloadapi/endpoint-resolution/resolve#endpointresolutioncontextproperty
            for all the names that are documented by Microsoft Fabric. The numeric
            value for "TenantId" is 3.
        value:
          type: string
          description: The value of the context property
    resolutionRequest:
      title: Resolution Request
      description: The payload to supply in order to resolve an endpoint.
      properties:
        context:
          type: array
          items:
            $ref: "#/components/schemas/resolutionContextProperty"
          description: The array of context properties.
    resolutionResponse:
      title: Resolution response
      description: The response to an endpoint resolution request.
      properties:
        ttlInMinutes:
          type: number
          description: The number of minutes this resolution result is valid.
        url:
          type: string
          description: The base URL of a Viya deployment.
    userError:
      title: User Error
      description: The error interface for user error.
      properties:
        message:
          type: string
          description: The error message.
  examples:
    errorResponse:
      description: Example of an error response going back to Microsoft Fabric.
      value:
        message: failed to resolve endpoint for tenant d2d365d1-a833-47fa-ad30-a402a096b1b3
          - database connection refused
        errorCode: "104"
        source: System
        isPermanent: false
    mappingResponse:
      description: The response to the request for the SAS Viya deployment that backs
        the Microsoft Fabric tenant 6e74ccf1-bc11-46a4-96d3-38a7cda7e37e.
      value:
        tenantId: 6e74ccf1-bc11-46a4-96d3-38a7cda7e37e
        region: Central US
        url: https://ght76.decisionbuilder.sas.com
    newMappingResponse:
      description: The response for recording a new mapping of Microsoft Fabric tenant
        to SAS Viya deployment.
      value:
        id: cfda6304-b661-473f-b017-c38bdecd79ec
    operationError:
      description: An error coming from an operation.
      value:
        message: Connection is closed.
    recordMappingRequest:
      description: The payload for mapping Microsoft Fabric tenant 6e74ccf1-bc11-46a4-96d3-38a7cda7e37e
        to its backing SAS Viya deployment.
      value:
        tenantId: 6e74ccf1-bc11-46a4-96d3-38a7cda7e37e
        tenantRegion: Central US
        viyaUrl: https://ght76.decisionbuilder.sas.com
    resolutionRequest:
      description: The payload for resolving the SAS Viya deployment that backs the
        Microsoft Fabric tenant 6e74ccf1-bc11-46a4-96d3-38a7cda7e37e.
      value:
        context:
        - name: 3
          value: 6e74ccf1-bc11-46a4-96d3-38a7cda7e37e
    resolutionResponse:
      description: The payload for resolving the SAS Viya deployment that backs the
        Microsoft Fabric tenant 6e74ccf1-bc11-46a4-96d3-38a7cda7e37e.
      value:
        ttlInMinutes: 5
        url: https://ght76.decisionbuilder.sas.com
    userError:
      description: User error.
      value:
        message: The tenant ID is not in the correct format.
