---
openapi: 3.0.3
info:
  title: Geo Enrichment
  version: "3"
  contact:
    name: SAS Developers
    url: https://developer.sas.com
    email: devex@sas.com
  description: The GeoEnrichment API imports Esri data into exiting CAS table
servers:
- url: http://example.com/geoEnrichment
  description: Mock server
tags:
- name: Root
  description: Contains operations for the root resource.
- name: Geocode
  description: Contains operations for the Geocode resource.
- name: Enrich
  description: Contains operations for the Enrich resource.
paths:
  /:
    get:
      summary: Get a collection of top-level links
      description: Returns a collection of links to the top-level collections
      operationId: root
      tags:
      - Root
      responses:
        "200":
          description: Version information about the API, as well as top level API
            entry points.
          headers:
            Content-Type:
              description: Media type of response
              schema:
                type: string
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                one:
                  $ref: "#/components/examples/rootGetExample"
            application/json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                one:
                  $ref: "#/components/examples/rootGetExample"
  /geocode/credits:
    post:
      description: Find the estimated credit usage for this geocode job request. This
        call is an extended GET operation and therefore idempotent and safe.
      summary: Credits used with the operation
      operationId: getGeocodeCredits
      requestBody:
        $ref: "#/components/requestBodies/geocodeJobRequest"
      tags:
      - Geocode
      responses:
        "200":
          description: Returned estimated credit usage for requested geocode job.
          headers:
            Content-Type:
              description: Media type of response
              schema:
                type: string
          content:
            text/plain:
              schema:
                type: string
              example: "5.25"
        "400":
          description: The credits cannot be retrieved because of error
          content:
            application/vnd.sas.error:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                one:
                  $ref: "#/components/examples/error400Example"
  /geocode/previews/address:
    post:
      description: Create an address string value for columns in the cas table. This
        call is an extended GET operation and therefore idempotent and safe.
      summary: Address string to geocode
      operationId: getSampleAddress
      requestBody:
        content:
          application/vnd.sas.geo.enrichment.table:
            schema:
              $ref: "#/components/schemas/table"
            examples:
              one:
                $ref: "#/components/examples/geocodePreviewsAddressExample"
          application/json:
            schema:
              $ref: "#/components/schemas/table"
            examples:
              one:
                $ref: "#/components/examples/geocodePreviewsAddressExample"
        description: Table model with cas table information
      tags:
      - Geocode
      responses:
        "200":
          description: Returned address string value for the given columns in CAS
            table
          headers:
            Content-Type:
              description: Media type of response
              schema:
                type: string
          content:
            text/plain:
              schema:
                type: string
              example: "123 Main Street, Anytown, ST"
        "400":
          description: The address string value cannot be retrieved because of error
          content:
            application/vnd.sas.error:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                one:
                  $ref: "#/components/examples/error400Example"
  /geocode/previews/location:
    get:
      description: Geocode a single address for preview
      summary: Geocode a single address
      operationId: getLocation
      parameters:
      - name: address
        in: query
        description: An address string
        required: true
        schema:
          type: string
          minLength: 2
          maxLength: 300
      tags:
      - Geocode
      responses:
        "200":
          description: Returned geocoded value (x, y and score)
          headers:
            Content-Type:
              description: Media type of response
              schema:
                type: string
          content:
            text/plain:
              schema:
                type: string
              example: "x=-78.83 y=35.73 score=100"
        "400":
          description: The address cannot be goecoded because of error
          content:
            application/vnd.sas.error:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                one:
                  $ref: "#/components/examples/error400Example"
  /enrich/credits:
    post:
      description: Find the estimated credit usage for this geo-enrich job request.
        This call is an extended GET operation and therefore idempotent and safe.
      summary: Credits used with the operation
      operationId: getEnrichCredits
      requestBody:
        $ref: "#/components/requestBodies/enrichJobRequest"
      tags:
      - Enrich
      responses:
        "200":
          description: Returned estimated credit usage for requested geo-enrich job
          headers:
            Content-Type:
              description: Media type of response
              schema:
                type: string
          content:
            text/plain:
              schema:
                type: string
              example: "5.25"
        "400":
          description: The credits cannot be retrieved because of error
          content:
            application/vnd.sas.error:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                one:
                  $ref: "#/components/examples/error400Example"
  /enrich/countries:
    get:
      description: Get a map of available country 2-letter ISO codes and associated
        country name for geo-enrichment.  The returned collection does not support
        filtering, sorting or pagination.
      summary: Get a list of countries
      operationId: getCountries
      tags:
      - Enrich
      responses:
        "200":
          description: Returned map of 2-letter ISO country codes associated with
            country name  that are available for geo-enrichment.
          headers:
            Content-Type:
              description: Media type of response
              schema:
                type: string
          content:
            application/vnd.sas.json:
              schema:
                $ref: "#/components/schemas/countries"
              examples:
                one:
                  $ref: "#/components/examples/enrichCountriesResponseExample"
            application/json:
              schema:
                $ref: "#/components/schemas/countries"
              examples:
                one:
                  $ref: "#/components/examples/enrichCountriesResponseExample"
        "500":
          description: Unknown error, unable to retrieve values from Esri
          content:
            application/vnd.sas.error:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                one:
                  $ref: "#/components/examples/error500Example"
  /enrich/capabilities:
    get:
      description: Get the available geographic layers and demographic columns for
        a given country.
      summary: Capabilities supported by a country
      operationId: getCapabilities
      parameters:
      - name: country
        in: query
        description: A 2- or 3-letter ISO country code.
        required: true
        schema:
          type: string
          minLength: 2
          maxLength: 3
      tags:
      - Enrich
      responses:
        "200":
          description: Returned capabilities for requested country.
          headers:
            Content-Type:
              description: Media type of response
              schema:
                type: string
          content:
            application/vnd.sas.geo.enrichment.capabilities:
              schema:
                $ref: "#/components/schemas/capability"
              examples:
                one:
                  $ref: "#/components/examples/enrichCapabilitiesResponseExample"
            application/json:
              schema:
                $ref: "#/components/schemas/capability"
              examples:
                one:
                  $ref: "#/components/examples/enrichCapabilitiesResponseExample"
        "404":
          description: Country not found
          content:
            application/vnd.sas.error:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                one:
                  $ref: "#/components/examples/error404Example"
        "500":
          description: Unknown error retrieving values from Esri
          content:
            application/vnd.sas.error:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                one:
                  $ref: "#/components/examples/error500Example"
components:
  requestBodies:
    geocodeJobRequest:
      content:
        application/vnd.sas.job+json:
          schema:
            $ref: "#/components/schemas/geocodeJobRequest"
          examples:
            json:
              $ref: "#/components/examples/geocodeCreditsExample"
        application/json:
          schema:
            $ref: "#/components/schemas/geocodeJobRequest"
          examples:
            json:
              $ref: "#/components/examples/geocodeCreditsExample"
      description: Job with job request to be executed
    enrichJobRequest:
      content:
        application/vnd.sas.job+json:
          schema:
            $ref: "#/components/schemas/enrichJobRequest"
          examples:
            json:
              $ref: "#/components/examples/geoenrichCreditsExample"
        application/json:
          schema:
            $ref: "#/components/schemas/geocodeJobRequest"
          examples:
            json:
              $ref: "#/components/examples/geoenrichCreditsExample"
      description: Job with job request to be executed
  schemas:
    job:
      description: The execution job.
      properties:
        version:
          type: integer
          description: version of the schema
        id:
          type: string
          description: unique id
        jobRequest:
          $ref: "#/components/schemas/geocodeJobRequest"
        state:
          type: string
          description: Current state of the job
        results:
          type: object
          description: output of the job execution
    geocodeJobRequest:
      type: object
      description: A job request with job definition and arguments for execution
      properties:
        version:
          type: integer
          description: version of schema
          example: 1
        name:
          type: string
          description: name of the job execution provider. This is 'GEOENRICHMENT'.
          example: "GEOCODE"
        jobDefinition:
          $ref: "#/components/schemas/geocodeJobDefinition"
        arguments:
          type: object
          description: a map of parameter(job definition) keys and values for job
            execution
          example:
            key: value
    enrichJobRequest:
      type: object
      description: A job request with job definition and arguments for execution
      properties:
        version:
          type: integer
          description: version of schema
          example: 1
        name:
          type: string
          description: name of the job execution provider. This is 'GEOENRICHMENT'.
          example: "GEOENRICHMENT"
        jobDefinition:
          $ref: "#/components/schemas/enrichJobDefinition"
        arguments:
          type: object
          description: a map of parameter(job definition) keys and values for job
            execution
          example:
            "key": "value"
    geocodeJobDefinition:
      type: object
      description: Details of the job
      properties:
        version:
          type: integer
          description: version of the scehma
        name:
          type: string
          description: name of the job execution provider. This is 'GEOENRICHMENT'.
        parameters:
          type: array
          description: items of type geocodeParameters
          items:
            $ref: "#/components/schemas/geocodeParameters"
        code:
          type: string
          description: Not used
    enrichJobDefinition:
      type: object
      description: Details of the job
      properties:
        version:
          type: integer
          description: version of the scehma
        name:
          type: string
          description: name of the job execution provider. This is 'GEOENRICHMENT'.
        parameters:
          type: array
          description: items of type enrichParameters
          items:
            $ref: "#/components/schemas/enrichParameters"
        code:
          type: string
          description: Not used
    geocodeParameters:
      description: geocode parameters used in jobDefinition
      properties:
        version:
          type: integer
          description: version of the parameters model
        name:
          type: string
          description: name of the parameter
        defaultValue:
          type: string
          description: default value of the parameter
        type:
          type: string
          description: type of the parameter value
        required:
          type: boolean
          description: is the parameter required in the arguments map
    enrichParameters:
      description: geocode parameters used in jobDefinition
      properties:
        version:
          type: integer
          description: version of the parameters model
        name:
          type: string
          description: name of the parameter
        defaultValue:
          type: string
          description: default value of the parameter
        type:
          type: string
          description: type of the parameter value
        required:
          type: boolean
          description: is the parameter required in the arguments map
    capability:
      description: Available geographic layers and demographic columns for a given
        country. All the parameters are required
      properties:
        version:
          type: integer
          description: Version of this media type
        country:
          type: string
          description: A 2- or 3-letter ISO country code.
        layers:
          description: The list of available geographic layers available to retrieve
            enrichment data for. These are defined [here](https://developers.arcgis.com/documentation/mapping-apis-and-services/demographics/tools/data-attribute-finder/).
          type: array
          items:
            $ref: "#/components/schemas/layer"
        categories:
          type: array
          description: The list of available demographic categories for the given
            country.
          items:
            $ref: "#/components/schemas/enrichNode"
    enrichNode:
      description: Capability node of type category, subcategory, datacollection
      properties:
        name:
          type: string
          description: The name of the node.
        label:
          type: string
          description: A user-friendly label.
        description:
          type: string
          description: A description of the contents of this node.
        type:
          type: string
          description: Type of node - CATEGORY, SUBCATEGORY, DATACOLLECTION, VARIABLE
        children:
          type: array
          description: The list of child enrichNodes
          items:
            $ref: "#/components/schemas/enrichNode"
    layer:
      description: Layer
      properties:
        version:
          type: integer
          description: version of the scehma
        name:
          type: string
          description: The name of the layer, for example Zipcode.
        id:
          type: string
          description: A unique id.
    table:
      description: Cas table with geographic columns
      properties:
        version:
          type: integer
          description: version of the scehma
        serverName:
          type: string
          description: cas server name
        sessionId:
          type: string
          description: cas session id
          format: uuid
        caslib:
          type: string
          description: cas library
        tableName:
          type: string
          description: table name
        columns:
          type: array
          description: column name and type
          items:
            $ref: "#/components/schemas/column"
    column:
      description: Geographic column in cas table
      properties:
        name:
          type: string
          description: column name
        type:
          type: string
          description: column type
    countries:
      description: Country
      type: object
      additionalProperties:
        type: string
      example:
        AL: Albania
    api:
      title: API
      description: The list of links to top-level resources and operations available
        from the root of the API.
      x-sas-media-type:
        name: application/vnd.sas.api
        version: 1
      required:
      - version
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
          minimum: 1
        links:
          description: The API's top-level links.
          type: array
          items:
            $ref: "#/components/schemas/link"
    error2:
      title: Error
      type: object
      description: The representation of an error.
      x-sas-media-type:
        name: application/vnd.sas.error
        version: 2
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The message for the error.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred.
          items:
            $ref: "#/components/schemas/error2"
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
    link:
      title: Link
      type: object
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
  examples:
    rootGetExample:
      summary: Root response
      description: Root response
      value: {"version": 1, "links": [{"method": "GET", "rel": "self", "href": "/geoEnrichment",
            "uri": "/geoEnrichment", "type": "application/vnd.sas.api"}, {"method": "GET",
            "rel": "/geocode", "href": "/geoEnrichment/geocode", "uri": "/geoEnrichment/geocode",
            "type": "application/vnd.sas.api"}, {"method": "GET", "rel": "/enrich",
            "href": "/geoEnrichment/enrich", "uri": "/geoEnrichment/enrich", "type": "application/vnd.sas.api"}]}
    error400Example:
      summary: 400 Error
      description: 400 Error
      value: {"message": "An error occurred.", "errorCode": 90001, "httpStatusCode": 400,
        "details": ["An error occurred."], "errors": ["An error occurred."], "version": 1}
    error404Example:
      summary: 404 Error
      description: 404 Error
      value: {"message": "An error occurred.", "errorCode": 90004, "httpStatusCode": 404,
        "details": ["An error occurred."], "errors": ["An error occurred."], "version": 1}
    error500Example:
      summary: 500 Error
      description: 500 Error
      value: {"message": "An error occurred.", "errorCode": 90005, "httpStatusCode": 500,
        "details": ["An error occurred."], "errors": ["An error occurred."], "version": 1}
    enrichCountriesResponseExample:
      summary: Countries
      description: Countries
      value:
        "AL": "Albania"
        "DZ": "Algeria"
    geocodePreviewsAddressExample:
      summary: Address preview
      description: Address preview
      value: {"version": 1, "serverName": "casServerName", "caslib": "caslibName",
        "tableName": "tableName", "columns": ["name": "street", "type": "CHAR", "name": "city",
          "type": "CHAR", "name": "state", "type": "CHAR", "name": "zip", "type": "NUMERIC",
          "name": "name", "type": "NUMERIC"]}
    enrichCapabilitiesResponseExample:
      summary: Capabilities response
      description: Capabilities response
      value: {"version": 1, "country": "US", "layers": ["version": 1, "name": "States",
          "id": "US.States", "version": 1, "name": "DMAs", "id": "US.DMA", {"version": 1,
            "name": "Congressional Districts", "id": "US.CD"}, "version": 1, "name": "CBSAs",
          "id": "US.CBSA", "version": 1, "name": "Counties", "id": "US.Counties",
          "version": 1, "name": "County Subdivisions", "id": "US.CSD", "version": 1,
          "name": "ZIP Codes", "id": "US.ZIP5", {"version": 1, "name": "Cities and\
              \ Towns (Places)", "id": "US.Places"}, "version": 1, "name": "Census\
              \ Tracts", "id": "US.Tracts", "version": 1, "name": "Block Groups",
          "id": "US.BlockGroups"], "categories": [{"version": 1, "name": "Age", "label": "Age",
            "type": "CATEGORY", "description": "Age Category", "children": [{"version": 1,
                "name": "1yearincrements", "label": "1 Year Increments", "type": "DATACOLLECTION",
                "description": "The 1 Year Increments data collection includes population\
                  \ counts by 1-year age breaks up to age 84 for 2021 and 2026.  The\
                  \ collection also includes 2010 population by single year increments\
                  \ up to age 21.  The data tables include age for total population\
                  \ and age by gender.  This collection contains data from Esri's\
                  \ 2021/2026 Updated Demographic database and Esri's Census 2010\
                  \ database.", "children": [{"version": 1, "name": "2021 Age: 1 Year\
                      \ Increments (Esri)", "label": "2021 Age: 1 Year Increments\
                      \ (Esri)", "type": "SUBCATEGORY", "description": "2021 Age:\
                      \ 1 Year Increments (Esri)", "children": [{"version": 1, "name": "AGE0_CY",
                        "label": "2021 Population Age <1", "type": "VARIABLE", "description": "2021\
                          \ Total Population Age <1 (Esri)", "dataType": "decimal",
                        "leaf": true}], "leaf": false}], "leaf": false}], "leaf": false}]}
    geocodeCreditsExample:
      summary: Credits example request
      description: Example request body for submitting a request to obtain a credits
        value.
      value:
        version: 3
        name: "GEOCODE"
        jobDefinition:
          version: 1
          type: "GEOCODE"
          parameters:
          - version: 1
            name: "token"
            defaultValue: "token"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "requestType"
            defaultValue: "GEOCODE"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "serverName"
            defaultValue: "serverName"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "caslib"
            defaultValue: "caslibName"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "tableName"
            defaultValue: "tableName"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "sessionId"
            defaultValue: "sessionId"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "geoColumnName"
            defaultValue: "geoColumnName"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "geoColumnType"
            defaultValue: "geoColumnType"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "outCaslib"
            defaultValue: "caslibName"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "outTableName"
            defaultValue: "tableName"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "country"
            defaultValue: "countryValue"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "layer"
            defaultValue: "layerValue"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "columnNames"
            defaultValue: "columnNames"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "columnTypes"
            defaultValue: "columnTypes"
            type: "CHARACTER"
            required: true
        arguments:
          token: "TOKEN"
          requestType: "GEOCODE"
          serverName: "server"
          sessionId: "sessionId"
          caslib: "caslib"
          tableName: "tableName"
          geoColumnName: "geoColumnName"
          geoColumnType: "varchar"
          outCaslib: "caslibName"
          outTableName: "tableName"
          country: "countryValue"
          layer: "layerValue"
          columnNames: "columnNames"
          columntypes: "columnTypes"
    geoenrichCreditsExample:
      summary: Credits example request
      description: Example request body for submitting a request to obtain a credits
        value.
      value:
        version: 3
        name: "GEOENRICH"
        jobDefinition:
          version: 1
          type: "GEOENRICH"
          parameters:
          - version: 1
            name: "token"
            defaultValue: "token"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "requestType"
            defaultValue: "GEOENRICH"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "serverName"
            defaultValue: "serverName"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "caslib"
            defaultValue: "caslibName"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "tableName"
            defaultValue: "tableName"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "sessionId"
            defaultValue: "sessionId"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "geoColumnName"
            defaultValue: "geoColumnName"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "geoColumnType"
            defaultValue: "geoColumnType"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "outCaslib"
            defaultValue: "caslibName"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "outTableName"
            defaultValue: "tableName"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "country"
            defaultValue: "countryValue"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "layer"
            defaultValue: "layerValue"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "columnNames"
            defaultValue: "columnNames"
            type: "CHARACTER"
            required: true
          - version: 1
            name: "columnTypes"
            defaultValue: "columnTypes"
            type: "CHARACTER"
            required: true
        arguments:
          token: "TOKEN"
          requestType: "GEOENRICH"
          serverName: "server"
          sessionId: "sessionId"
          caslib: "caslib"
          tableName: "tableName"
          geoColumnName: "geoColumnName"
          geoColumnType: "varchar"
          outCaslib: "caslibName"
          outTableName: "tableName"
          country: "countryValue"
          layer: "layerValue"
          columnNames: "columnNames"
          columntypes: "columnTypes"
