---
openapi: 3.0.3
info:
  version: "1"
  title: SAS Risk KRM Proxy
  description: >
    The SAS Risk KRM API Proxy exposes a single endpoint that fetches content from
    a specified destination path.
    The SAS Risk KRM API Proxy acts as a sidecar container authenticating and authorizing
    the user login and
    directing the request provided to the underlying SAS KRM API container.
  termsOfService: "https://www.sas.com/en_us/legal/copyright.html"
  contact:
    name: SAS Developers
    url: https://developer.sas.com
    email: devex@sas.com
servers:
- url: https://example.com/riskKRMAPIProxy
  description: Base path for the proxy endpoint
tags:
- name: Proxy
  description: Operations for relaying requests to configured KRM destinations.
paths:
  /:
    get:
      tags:
      - Proxy
      operationId: root
      summary: Root resource for the KRM proxy API
      description: Returns metadata for the proxy API root resource.
      responses:
        "200":
          description: Root resource metadata.
          headers:
            ETag:
              description: Entity tag for conditional requests.
              schema:
                type: string
            Last-Modified:
              description: Last modification timestamp (HTTP-date, RFC 7231).
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
              example:
                description: SAS Risk KRM API Proxy root metadata
            application/vnd.sas.api+json:
              schema:
                type: object
                additionalProperties: true
              example:
                description: SAS Risk KRM API Proxy root metadata
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
  /{sasKrmApiPath}:
    get:
      tags:
      - Proxy
      operationId: getProxyResource
      summary: Relay content from specified destination path
      description: Relay content from a specified destination URL.
      parameters:
      - $ref: "#/components/parameters/restPath"
      - $ref: "#/components/parameters/ifNoneMatch"
      - $ref: "#/components/parameters/ifModifiedSince"
      responses:
        "200":
          description: Successful relay response.
          headers:
            ETag:
              description: Entity tag for conditional requests.
              schema:
                type: string
            Last-Modified:
              description: Last modification timestamp (HTTP-date, RFC 7231).
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
              example:
                relay: successful
            application/vnd.sas.api+json:
              schema:
                type: object
                additionalProperties: true
              example:
                relay: successful
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
    head:
      tags:
      - Proxy
      operationId: headersForProxyResource
      summary: Relay content from specified destination path
      description: Relay content from a specified destination path.
      parameters:
      - $ref: "#/components/parameters/restPath"
      - $ref: "#/components/parameters/ifNoneMatch"
      - $ref: "#/components/parameters/ifModifiedSince"
      responses:
        "200":
          description: Successful relay headers.
          headers:
            ETag:
              description: Entity tag for conditional requests.
              schema:
                type: string
            Last-Modified:
              description: Last modification timestamp (HTTP-date, RFC 7231).
              schema:
                type: string
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
    post:
      tags:
      - Proxy
      operationId: createProxyResource
      summary: Relay content from specified destination path
      description: Relay content from a specified destination path.
      parameters:
      - $ref: "#/components/parameters/restPath"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
            example:
              relay: create
          application/vnd.sas.api+json:
            schema:
              type: object
              additionalProperties: true
            example:
              relay: create
      responses:
        "201":
          description: Destination resource was created.
          headers:
            ETag:
              description: Entity tag for conditional requests.
              schema:
                type: string
            Last-Modified:
              description: Last modification timestamp (HTTP-date, RFC 7231).
              schema:
                type: string
            Location:
              description: URI of the created resource.
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
              example:
                relay: created
            application/vnd.sas.api+json:
              schema:
                type: object
                additionalProperties: true
              example:
                relay: created
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
    put:
      tags:
      - Proxy
      operationId: updateRoot
      summary: Relay content from specified destination path
      description: Relay content from a specified destination path.
      parameters:
      - $ref: "#/components/parameters/restPath"
      - $ref: "#/components/parameters/ifMatch"
      - $ref: "#/components/parameters/ifUnmodifiedSince"
      responses:
        "200":
          description: Destination resource was replaced.
          headers:
            ETag:
              description: Entity tag for conditional requests.
              schema:
                type: string
            Last-Modified:
              description: Last modification timestamp (HTTP-date, RFC 7231).
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
              example:
                relay: replaced
            application/vnd.sas.api+json:
              schema:
                type: object
                additionalProperties: true
              example:
                relay: replaced
        "412":
          $ref: "#/components/responses/412"
        "428":
          $ref: "#/components/responses/428"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
    patch:
      tags:
      - Proxy
      operationId: patchRoot
      summary: Relay content from specified destination path
      description: Relay content from a specified destination path.
      parameters:
      - $ref: "#/components/parameters/restPath"
      responses:
        "200":
          description: Destination resource was updated.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
              example:
                relay: updated
            application/vnd.sas.api+json:
              schema:
                type: object
                additionalProperties: true
              example:
                relay: updated
        "412":
          $ref: "#/components/responses/412"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
    delete:
      tags:
      - Proxy
      operationId: deleteRoot
      summary: Relay content from specified destination path
      description: Relay content from a specified destination path.
      parameters:
      - $ref: "#/components/parameters/restPath"
      responses:
        "204":
          description: Destination resource was deleted.
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
components:
  parameters:
    restPath:
      name: sasKrmApiPath
      in: path
      description: Destination path to call
      required: true
      schema:
        type: string
    ifNoneMatch:
      name: If-None-Match
      in: header
      required: false
      description: Return representation only if ETag does not match.
      schema:
        type: string
    ifModifiedSince:
      name: If-Modified-Since
      in: header
      required: false
      description: Return representation only if modified since this HTTP-date (RFC
        7231).
      schema:
        type: string
      example: Sun, 06 Nov 1994 08:49:37 GMT
    ifMatch:
      name: If-Match
      in: header
      required: false
      description: Apply update only if ETag matches.
      schema:
        type: string
    ifUnmodifiedSince:
      name: If-Unmodified-Since
      in: header
      required: false
      description: Apply update only if resource has not changed since this HTTP-date
        (RFC 7231).
      schema:
        type: string
      example: Sun, 06 Nov 1994 08:49:37 GMT
  schemas:
    error:
      $ref: "#/components/schemas/error2"
    error2:
      title: Error
      type: object
      description: The representation of an error.
      x-sas-media-type:
        name: application/vnd.sas.error
        version: 2
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The message for the error.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred.
          items:
            $ref: "#/components/schemas/error2"
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
    link:
      title: Link
      type: object
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
  responses:
    "400":
      description: One or more arguments is invalid.
      headers:
        Content-Type:
          description: application/vnd.sas.error+json
          schema:
            type: string
        ETag:
          description: Current entity tag.
          schema:
            type: string
        Last-Modified:
          description: Last modification timestamp (HTTP-date, RFC 7231).
          schema:
            type: string
      content:
        application/vnd.sas.error+json:
          schema:
            $ref: "#/components/schemas/error"
          examples:
            missingParameter:
              value: {"version": 2, "httpStatusCode": 400, "message": "Bad Request",
                "details": ['You must specify the request parameter "sasKrmApiPath".',
                  "path: /riskKRMAPIProxy/", "correlator: a711bf91-32c1-4539-b6e7-cf33e13412a2"]}
    "403":
      description: The requested destination URL is forbidden.
      headers:
        Content-Type:
          description: application/vnd.sas.error+json
          schema:
            type: string
        ETag:
          description: Current entity tag.
          schema:
            type: string
        Last-Modified:
          description: Last modification timestamp (HTTP-date, RFC 7231).
          schema:
            type: string
      content:
        application/vnd.sas.error+json:
          schema:
            $ref: "#/components/schemas/error"
          example:
            version: 2
            httpStatusCode: 403
            message: Forbidden
            details:
            - "The following path cannot be accessed because it is not authorized:\
              \ 'sasKrmApiPath'. To gain access to the site, please ask your SAS Administrator."
            - "path: /missingParameter/"
            - "correlator: 6abc86c0-51da-4b40-97ac-c8700be0eee0"
    "412":
      description: The request precondition failed.
      headers:
        Content-Type:
          description: application/vnd.sas.error+json
          schema:
            type: string
        ETag:
          description: Current entity tag.
          schema:
            type: string
        Last-Modified:
          description: Last modification timestamp (HTTP-date, RFC 7231).
          schema:
            type: string
      content:
        application/vnd.sas.error+json:
          schema:
            $ref: "#/components/schemas/error"
          example:
            version: 2
            httpStatusCode: 412
            message: Precondition Failed
            details:
            - ETag or modification precondition did not match.
    "428":
      description: A required precondition header was missing.
      headers:
        Content-Type:
          description: application/vnd.sas.error+json
          schema:
            type: string
        ETag:
          description: Current entity tag.
          schema:
            type: string
        Last-Modified:
          description: Last modification timestamp (HTTP-date, RFC 7231).
          schema:
            type: string
      content:
        application/vnd.sas.error+json:
          schema:
            $ref: "#/components/schemas/error"
          example:
            version: 2
            httpStatusCode: 428
            message: Precondition Required
            details:
            - Required conditional header was not provided.


