---
openapi: 3.0.3
info:
  title: Indexer
  description: The SAS Visual Investigator Indexer API provides access to the background
    indexing process in SAS Visual Investigator. This provides clients with the ability
    to query and modify indexing process related options.
  version: '4'
  contact:
    name: SAS Developers
    url: 'https://developer.sas.com'
    email: devex@sas.com
servers:
- url: 'http://example.com/svi-indexer'
  description: An example URL including the base path for this API.
tags:
- name: Root
  description: The root of the API.
- name: Object Metadata
  description: An endpoint to retrieve object metadata related to indexing.
- name: Job Cancellation
  description: An endpoint to cancel an indexing job.
- name: Tuning Partitions
  description: Endpoints related to tuning parameters.
- name: Index Request
  x-sas-internal: true
  description: An endpoint to submit a request to index specific records.
- name: Configuration
  description: Endpoints related to importing and exporting configurations.
paths:
  /:
    get:
      tags:
      - Root
      operationId: root
      summary: Get a list of top-level links
      description: |
        Returns a list of links to the top-level resources surfaced through this API.
      responses:
        '200':
          description: Returns links for the Indexer service. Also used to determine
            whether the service provided by the API is available.
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: '#/components/schemas/api'
              examples:
                Api Example:
                  $ref: '#/components/examples/Top-Level-Links-Example'
            application/json:
              schema:
                $ref: '#/components/schemas/api'
              examples:
                Api Example:
                  $ref: '#/components/examples/Top-Level-Links-Example'
        '404':
          description: Service is not available
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                "404 Example":
                  $ref: '#/components/examples/Error-Not-Found'
            application/json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                "404 Example":
                  $ref: '#/components/examples/Error-Not-Found'
    head:
      tags:
      - Root
      summary: Get the headers for the API
      description: Returns the headers for the API. Also used to determine whether
        the service provided by the API is available.
      operationId: headersForRoot
      responses:
        '200':
          description: Returns the headers for the API. Also used to determine whether
            the service provided by the API is available.
  /objectMetadata:
    get:
      summary: Get object metadata
      tags:
      - Object Metadata
      responses:
        '200':
          description: Object metadata returned successfully.
          content:
            application/json:
              schema:
                allOf:
                - properties:
                    entities:
                      type: array
                      items:
                        $ref: '#/components/schemas/objectMetadataObject'
                - properties:
                    relationships:
                      type: array
                      items:
                        $ref: '#/components/schemas/objectMetadataObject'
                - properties:
                    transactions:
                      type: array
                      items:
                        $ref: '#/components/schemas/objectMetadataObject'
                type: object
              examples:
                Object metadata for entities and relationships:
                  $ref: '#/components/examples/Object-metadata-for-entities-and-relationships'
      operationId: getObjectMetadata
      description: Lists object metadata associated to indexing tasks.
  '/jobs/{jobId}':
    parameters:
    - schema:
        type: string
        format: uuid
      name: jobId
      in: path
      required: true
      description: The ID of the job being canceled.
    delete:
      summary: Cancel indexing job
      operationId: cancelJob
      responses:
        '200':
          description: Job has already been canceled.
        '202':
          description: Job cancellation has been accepted.
      description: Cancel a running indexing job.
      tags:
      - Job Cancellation
  /tuning/partitions:
    get:
      summary: Get tuning parameters
      tags:
      - Tuning Partitions
      responses:
        '200':
          description: Tuning parameters returned successfully.
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/baseCollection2'
                - type: object
                  properties:
                    items:
                      type: array
                      items:
                        $ref: '#/components/schemas/objectTuningParameters'
              examples:
                Tuning parameters for a document and relationship:
                  $ref: '#/components/examples/Tuning-parameters-for-a-document-and-relationship'
            application/vnd.sas.collection+json:
              schema:
                allOf:
                - $ref: '#/components/schemas/baseCollection2'
                - type: object
                  properties:
                    items:
                      type: array
                      items:
                        $ref: '#/components/schemas/objectTuningParameters'
              examples:
                Tuning parameters for a document and relationship:
                  $ref: '#/components/examples/Tuning-parameters-for-a-document-and-relationship'
      operationId: getTuningPartitions
      description: Gets all tuning parameters.
      parameters:
      - name: "Accept-Item"
        in: "header"
        description: Specifies the media type of the items returned.
        schema:
          type: "string"
          enum:
          - "application/vnd.sas.investigation.indexing.tuning.partition+json"
          - "application/vnd.sas.investigation.indexing.tuning.partition+json;version=1"
    put:
      summary: Update tuning parameters
      operationId: updateTuningPartitions
      responses:
        '200':
          description: Tuning parameters updated successfully.
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/baseCollection2'
                - type: object
                  properties:
                    items:
                      type: array
                      items:
                        $ref: '#/components/schemas/objectTuningParameters'
              examples:
                Tuning parameters for a document and relationship:
                  $ref: '#/components/examples/Tuning-parameters-for-a-document-and-relationship'
            application/vnd.sas.collection+json:
              schema:
                allOf:
                - $ref: '#/components/schemas/baseCollection2'
                - type: object
                  properties:
                    items:
                      type: array
                      items:
                        $ref: '#/components/schemas/objectTuningParameters'
              examples:
                Tuning parameters for a document and relationship:
                  $ref: '#/components/examples/Tuning-parameters-for-a-document-and-relationship'
        '400':
          description: Invalid request body has been provided.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                "400 Response Example":
                  $ref: '#/components/examples/Tuning-Partitions-Error-Invalid-Body'
      description: |-
        This endpoint can be used to create a new set of tuning parameters for a document, relationship, or transaction. Simply include the new set of parameters in the PUT.
        Omitting a set of tuning parameters for a document, relationship, or transaction from the PUT will delete it.
      requestBody:
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/baseCollection2'
              - type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/objectTuningParameters'
            examples:
              Updating document type tuning parameters:
                $ref: '#/components/examples/Updating-document-type-tuning-parameters'
          application/vnd.sas.collection+json:
            schema:
              allOf:
              - $ref: '#/components/schemas/baseCollection2'
              - type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/objectTuningParameters'
            examples:
              Updating document type tuning parameters:
                $ref: '#/components/examples/Updating-document-type-tuning-parameters'
        description: The request body for updating partitions.
      tags:
      - Tuning Partitions
      parameters:
      - name: "Accept-Item"
        in: "header"
        description: Specifies the media type of the items returned.
        schema:
          type: "string"
          enum:
          - "application/vnd.sas.investigation.indexing.tuning.partition+json"
          - "application/vnd.sas.investigation.indexing.tuning.partition+json;version=1"
      - name: "Content-Item-Type"
        in: "header"
        description: Specifies the media type of the items supplied.
        required: false
        schema:
          type: "string"
          enum:
          - "application/vnd.sas.investigation.indexing.tuning.partition+json"
          - "application/vnd.sas.investigation.indexing.tuning.partition+json;version=1"
  /indexRequest:
    post:
      summary: Submit an indexing request
      operationId: createIndexRequest
      x-sas-internal: true
      responses:
        '202':
          description: Indexing request has been accepted.
        '400':
          description: Invalid request body has been provided.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                "400 Response Example":
                  $ref: '#/components/examples/Index-Request-Error-Invalid-Body'
        '503':
          description: Operational indexing is toggled off.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                "503 Response Example":
                  $ref: '#/components/examples/Error-Service-Unavailable'
      description: An indexing request for the specified objects.
      tags:
      - Index Request
      requestBody:
        content:
          application/vnd.sas.investigation.indexing.request+json:
            schema:
              $ref: '#/components/schemas/indexRequest'
            examples:
              Operational Indexing Example:
                $ref: '#/components/examples/indexRequest'
              Detailed Transactions Example:
                $ref: '#/components/examples/indexRequestWithTransactions'
          application/json:
            schema:
              $ref: '#/components/schemas/indexRequest'
            examples:
              Operational Indexing Example:
                $ref: '#/components/examples/indexRequest'
              Detailed Transactions Example:
                $ref: '#/components/examples/indexRequestWithTransactions'
        description: Request body that contains the information to submit an indexing
          request for the specified objects.
  /indexRequest/version:
    get:
      tags:
      - Configuration
      summary: Gets the index format version
      description: Returns the index format version that this service supports
      operationId: getIndexFormatVersion
      responses:
        '200':
          description: The request succeeded.
          content:
            application/vnd.sas.sand.index.format.version.response+json:
              schema:
                $ref: '#/components/schemas/indexFormatVersionResponse'
              examples:
                api:
                  $ref: '#/components/examples/indexFormatVersionResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/indexFormatVersionResponse'
              examples:
                api:
                  $ref: '#/components/examples/indexFormatVersionResponse'
    head:
      tags:
      - Configuration
      summary: Gets the headers for the get index format version operation
      description: Returns the headers for the get index format version operation.
      operationId: headersForIndexFormatVersion
      responses:
        '200':
          description: The request succeeded.
          content:
            application/vnd.sas.sand.index.format.version.response+json:
              schema:
                $ref: '#/components/schemas/indexFormatVersionResponse'
              examples:
                api:
                  $ref: '#/components/examples/indexFormatVersionResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/indexFormatVersionResponse'
              examples:
                api:
                  $ref: '#/components/examples/indexFormatVersionResponse'
  /config:
    get:
      tags:
      - Configuration
      operationId: getConfiguration
      summary: Get the service configuration
      description: Get an export ZIP file of the configuration values for the service.
      responses:
        '200':
          description: The configuration for the service was successfully exported.
          content:
            application/zip:
              schema:
                $ref: '#/components/schemas/configurationObject'
            application/json:
              schema:
                $ref: '#/components/schemas/configurationObject'
    post:
      tags:
      - Configuration
      operationId: createImportConfigurationRequest
      summary: Import a service configuration
      description: Import an exported ZIP file of the configuration values for this
        service. Returns the number of imported resources.
      requestBody:
        content:
          application/zip:
            schema:
              $ref: '#/components/schemas/configurationObject'
      responses:
        '200':
          description: The configuration for the service was successfully imported.
          content:
            application/json:
              schema:
                type: string
        '400':
          description: The ZIP file is malformed or the resource contains invalid
            configuration.
          content:
            application/vnd.sas.error+json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                "400 Response Example":
                  $ref: '#/components/examples/Config-Error-Invalid-Body'
            application/json:
              schema:
                $ref: '#/components/schemas/error2'
              examples:
                "400 Response Example":
                  $ref: '#/components/examples/Config-Error-Invalid-Body'
components:
  schemas:
    objectMetadataObject:
      description: An individual object that contains the metadata about a certain
        object.
      type: object
      title: Object metadata
      properties:
        qualifiedName:
          type: string
          minLength: 1
        label:
          type: string
          minLength: 1
        queryColumns:
          type: string
          minLength: 1
        tableSize:
          type: number
          example: 0
        dedicatedSearchIndex:
          type: boolean
        tableName:
          type: string
          minLength: 1
        schemaName:
          type: string
          minLength: 1
        childObjects:
          type: array
          items:
            $ref: '#/components/schemas/childObjectMetadata'
      required:
      - qualifiedName
      - label
      - queryColumns
      - tableSize
      - dedicatedSearchIndex
      - tableName
      - schemaName
    childObjectMetadata:
      description: An individual object that contains the metadata about a child object.
      type: object
      title: Child object metadata
      properties:
        qualifiedName:
          type: string
          minLength: 1
        label:
          type: string
          minLength: 1
        queryColumns:
          type: string
          minLength: 1
        tableSize:
          type: number
        dedicatedSearchIndex:
          type: boolean
        tableName:
          type: string
          minLength: 1
        schemaName:
          type: string
          minLength: 1
      required:
      - qualifiedName
      - label
      - queryColumns
      - tableSize
      - dedicatedSearchIndex
      - tableName
      - schemaName
    api:
      title: API
      properties:
        links:
          description: The API's top-level links.
          items:
            $ref: '#/components/schemas/link'
          type: array
        version:
          description: The version number of the API representation. This is version
            1.
          minimum: 1
          type: integer
    error2:
      title: Error
      properties:
        details:
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
          type: array
        errorCode:
          description: The numeric ID for the error.
          type: integer
        errors:
          description: Any additional errors that occurred.
          items:
            $ref: '#/components/schemas/error2'
          type: array
        httpStatusCode:
          description: The HTTP status code for the error.
          type: integer
        id:
          description: The string ID for the error.
          type: string
        links:
          description: The links that apply to the error.
          items:
            $ref: '#/components/schemas/link'
          type: array
        message:
          description: The message for the error.
          type: string
        remediation:
          description: A message that describes how to resolve the error.
          type: string
        version:
          description: The version number of the error representation. This representation
            is version 2.
          type: integer
    link:
      title: Link
      properties:
        href:
          description: The URL for the link.
          type: string
          maxLength: 4000
        itemType:
          description: 'If this is a link to a container, `itemType` is the media
            type or link type for the items in the container.'
          type: string
          maxLength: 500
        method:
          description: The HTTP method for the link.
          type: string
        rel:
          description: The relationship of the link to the resource.
          type: string
          maxLength: 100
        responseItemType:
          description: 'The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.'
          type: string
          maxLength: 500
        responseType:
          description: 'The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.'
          type: string
          maxLength: 500
        title:
          description: The title for the link.
          type: string
          maxLength: 500
        type:
          description: The media type or link type for the link.
          type: string
          maxLength: 500
        uri:
          description: The relative URI for the link.
          type: string
          pattern: '^/.*$'
          maxLength: 4000
    baseCollection2:
      title: Base collection
      properties:
        accept:
          description: A space-delimited list of media types from which an `Accept`
            header can be constructed.
          type: string
          maxLength: 255
        count:
          description: If populated indicates the number of items in the collection.
          format: int64
          type: integer
          minimum: 0
        limit:
          description: The number of items that were requested for the collection.
          type: integer
          minimum: 0
        links:
          description: The links that apply to the collection.
          items:
            $ref: '#/components/schemas/link'
          type: array
        name:
          description: The name of the collection.
          type: string
          maxLength: 255
        start:
          description: The zero-based index of the first item in the collection.
          format: int64
          type: integer
          minimum: 0
        version:
          description: The version number of the collection representation. This representation
            is version 2.
          type: integer
          minimum: 0
    indexFormatVersionResponse:
      description: 'The response from /indexRequest/version requesting the index format
        version this service supports.'
      type: object
      properties:
        indexFormatVersion:
          description: the supported index format version
          type: integer
    objectTuningParameters:
      description: A holder of all tuning parameters for a certain object type.
      type: object
      properties:
        objectType:
          type: string
          minLength: 1
          enum:
          - DOCUMENT
          - RELATIONSHIP
          - TRANSACTION
          - GLOBAL_DOCUMENT
          - GLOBAL_RELATIONSHIP
          - GLOBAL_TRANSACTION
          example: DOCUMENT
          description: |-
            The type of metadata this partition tuning parameter applies to.

            DOCUMENT, RELATIONSHIP, or TRANSACTION for per object tuning.

            GLOBAL_DOCUMENT, GLOBAL_RELATIONSHIP, or GLOBAL_TRANSACTION for global default.
        objectName:
          type: string
          minLength: 1
          example: intel_report
          description: |-
            The fully qualified name of the object that this partition tuning parameter applies to (for example, intel_report).

            It is equal to `objectType` in the case of the global defaults.
        parameters:
          type: array
          uniqueItems: true
          minItems: 1
          description: Array of partition tuning parameters for this object.
          items:
            $ref: '#/components/schemas/objectTuningParameter'
        version:
          type: string
          minLength: 1
      required:
      - objectType
      - objectName
      - parameters
      - version
      title: Object tuning parameters
    objectTuningParameter:
      title: Object tuning parameter
      description: An object that holds individual parameters for object tuning.
      type: object
      properties:
        parameter:
          type: string
          minLength: 1
          description: The name of the tuning parameter.
          enum:
          - partitionMultiplier
          - partitionSize
          - chunkSize
          example: chunkSize
        value:
          type: number
          description: The value set for the tuning parameter.
          example: 2000
        defaultValue:
          type: number
          description: Immutable. Indicates the default value. Set only for GLOBAL_...
            tuning parameters.
          example: 2000
          readOnly: true
      required:
      - parameter
      - value
    indexRequest:
      title: Index Request
      type: object
      description: An object that holds information required to index documents, relationships,
        and transactions.
      x-sas-internal: true
      properties:
        documents:
          type: array
          items:
            $ref: '#/components/schemas/documentIndexRequest'
        relationships:
          type: array
          items:
            $ref: '#/components/schemas/relationshipIndexRequest'
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/transactionIndexRequest'
    documentIndexRequest:
      title: Document index request
      type: object
      x-sas-internal: true
      description: An object that holds information required to index a document.
      properties:
        type:
          type: string
          description: The entity type.
          pattern: '^[a-zA-Z0-9_\.-]*$'
          maxLength: 25
        index:
          type: array
          description: The IDs of documents to be indexed.
          items:
            type: string
        delete:
          type: array
          description: The IDs of documents to be deleted from the search index.
          items:
            type: string
      required:
      - type
    relationshipIndexRequest:
      title: Relationship index request
      type: object
      x-sas-internal: true
      description: |
        An object that holds information required to index a relationship.

        The fully qualified relationship identifiers are made out of four or five parts, either: $relationshipName|\_|$fromObjectName|\_|$toObjectName|\_|$primaryKey when a primary key for the relationship exists, or $relationshipName|\_|$fromObjectName|\_|$toObjectName|\_|$fromObjectReference|\_|$toObjectReference otherwise.
      properties:
        relationshipName:
          type: string
          description: The name of the relationship.
          pattern: '^[a-zA-Z0-9_\.-]*$'
          maxLength: 25
        fromObjectName:
          type: string
          description: The name of the entity type the relationship links from.
          pattern: '^[a-zA-Z0-9_\.-]*$'
          maxLength: 25
        toObjectName:
          type: string
          description: The name of the entity type the relationship links to.
          pattern: '^[a-zA-Z0-9_\.-]*$'
          maxLength: 25
        index:
          type: array
          description: The IDs of relationships to index.
          items:
            type: string
        delete:
          type: array
          description: The IDs of relationships to delete from the search index.
          items:
            type: string
      required:
      - relationshipName
      - fromObjectName
      - toObjectName
    transactionIndexRequest:
      title: Transaction index request
      type: object
      x-sas-internal: true
      description: |
        The format of the transaction identifiers depends on the entity types selected for the transaction:
        - When a single entity type is selected for both "from" and "to" entities, the identifier is composed of two parts: $fromObjectId-_-$toObjectId
        - When "multiple types" is selected for the "from" entity and a single entity type for the "to" entity, the identifier is composed of three parts: $fromObjectName-_-$fromObjectId-_-$toObjectId
        - When a single entity type is selected for the "from" entity and "multiple types" is selected for the "to" entity, the identifier is composed of three parts: $fromObjectId-_-$toObjectName-_-$toObjectId
        - When "multiple types" is selected for both "from" and "to" entities, the identifier is composed of four parts: $fromObjectName-_-$fromObjectId-_-$toObjectName-_-$toObjectId

        In cases where an entity type has a composite key, the $objectId part should contain the composite key values separated by "-_-".
      properties:
        transactionName:
          type: string
          description: The name of the transaction.
          pattern: '^[a-zA-Z0-9_\.-]*$'
          maxLength: 25
        index:
          type: array
          description: The IDs of transactions to be indexed.
          items:
            type: string
        delete:
          type: array
          description: The IDs of transactions to delete from the search index.
          items:
            type: string
      required:
      - transactionName
    configurationObject:
      title: Configuration Object
      description: A ZIP file that represents the Indexer configuration.
      type: string
      format: binary
    indexingJobRequest:
      title: Indexing Job Request
      type: object
      description: An object that holds information for an indexing job request that
        is submitted through the Environment Manager's Jobs and Flows section.
      properties:
        indexType:
          type: string
          description: The type of indexing job (FULL or INCREMENTAL).
          enum:
          - FULL
          - INCREMENTAL
        since:
          type: string
          format: date-time
          description: The UTC timestamp (ISO-8601 format) for incremental indexing.
            For incremental jobs, the since field determines the starting point for
            indexing. If not provided, Indexer will fall back to the last successful
            run time recorded for a given object, ensuring that no changes are missed.
          example: '2017-01-12T14:40:03.000Z'
        indexAssociatedObjects:
          type: boolean
          description: Determines whether associated objects should also be indexed.
          default: true
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/indexingTaskRequest'
      required:
      - indexType
    indexingTaskRequest:
      title: Indexing Task Request
      type: object
      description: An object that holds information for an indexing task within an
        indexing job request.
      properties:
        type:
          type: string
          description: The type of object (ENTITY, RELATIONSHIP, or TRANSACTION).
          enum:
          - ENTITY
          - RELATIONSHIP
          - TRANSACTION
        name:
          type: string
          description: The name of the object to be indexed.
        fromObjectName:
          type: string
          description: The name of the originating object. This field is only required
            for tasks of type RELATIONSHIP.
      required:
      - type
      - name
  examples:
    Error-Service-Unavailable:
      x-sas-internal: true
      description: An example of a 503 service unavailable error message.
      value:
        httpStatusCode: 503
        errorCode: "503"
        message: Operational indexing is toggled off.
        details:
          traceId: "de2501a808f1fa39"
          path: "/svi-indexer/indexRequest"
        remediation: ""
        links: []
        version: 2
    Config-Error-Invalid-Body:
      description: An example of a 400 invalid body error message.
      value:
        httpStatusCode: 400
        errorCode: "400"
        message: The ZIP file is malformed or the resource contains invalid configuration.
        details: []
        remediation: ""
        links: []
        version: 1
    Index-Request-Error-Invalid-Body:
      description: An example of a 400 invalid body error message.
      value:
        httpStatusCode: 400
        errorCode: size_constraint_violation_parameter
        message: The value of the parameter named "relationships[0].relationshipName"
          must be at most 25 characters long.
        details: []
        remediation: ""
        links: []
        version: 1
    Tuning-Partitions-Error-Invalid-Body:
      description: An example of a 400 invalid body error message.
      value:
        httpStatusCode: 400
        errorCode: tuning_global_parameters_must_be_supplied
        message: "Global parameters (GLOBAL_DOCUMENT, GLOBAL_RELATIONSHIP, GLOBAL_TRANSACTION)\
          \ must all be supplied."
        details: []
        remediation: ""
        links: []
        version: 1
    Error-Not-Found:
      description: An example of a 404 resource not found error message.
      value:
        httpStatusCode: 404
        errorCode: "404"
        message: Not Found
        details:
        - "path: /svi-indexer/"
        remediation: ""
        links: []
        version: 1
    Top-Level-Links-Example:
      description: An example of a response from /svi-indexer listing the top-level
        links.
      value:
        version: 1
        links:
        - method: GET
          rel: exportConfig
          href: /svi-indexer/config
          uri: /svi-indexer/config
          responseType: application/zip
        - method: POST
          rel: importConfig
          href: /svi-indexer/config
          uri: /svi-indexer/config
          responseType: application/json
        - method: DELETE
          rel: cancelJob
          href: /svi-indexer/jobs
          uri: /svi-indexer/jobs
        - method: GET
          rel: getObjectIndexingMetadata
          href: /svi-indexer/objectMetadata
          uri: /svi-indexer/objectMetadata
          responseType: application/vnd.sas.investigation.indexing.metadata
        - method: GET
          rel: getPartitionTuningParameters
          href: /svi-indexer/tuning/partitions
          uri: /svi-indexer/tuning/partitions
          responseType: application/vnd.sas.collection
          responseItemType: application/vnd.sas.investigation.indexing.tuning.partition
        - method: PUT
          rel: updatePartitionTuningParameters
          href: /svi-indexer/tuning/partitions
          uri: /svi-indexer/tuning/partitions
          responseType: application/vnd.sas.collection
          responseItemType: application/vnd.sas.investigation.indexing.tuning.partition
    Updating-document-type-tuning-parameters:
      description: Valid tuning parameters to update a document. All GLOBAL must always
        be supplied.
      value:
        name: partitionTuningParameters
        version: 1
        items:
        - objectType: GLOBAL_DOCUMENT
          objectName: GLOBAL_DOCUMENT
          parameters:
          - parameterName: chunkSize
            value: 1000
            defaultValue: 2000
          - parameterName: partitionSize
            value: 1000
            defaultValue: 50000
          - parameterName: partitionMultiplier
            value: 1
            defaultValue: 1
        - objectType: GLOBAL_RELATIONSHIP
          objectName: GLOBAL_RELATIONSHIP
          parameters:
          - parameterName: chunkSize
            value: 1000
            defaultValue: 2000
          - parameterName: partitionSize
            value: 1000
            defaultValue: 50000
          - parameterName: partitionMultiplier
            value: 1
            defaultValue: 1
        - objectType: GLOBAL_TRANSACTION
          objectName: GLOBAL_TRANSACTION
          parameters:
          - parameterName: chunkSize
            value: 1000
            defaultValue: 2000
          - parameterName: partitionSize
            value: 1000
            defaultValue: 50000
          - parameterName: partitionMultiplier
            value: 1
            defaultValue: 1
        - objectType: DOCUMENT
          objectName: intel_report
          parameters:
          - parameterName: partitionMultiplier
            value: 1.5
          - parameterName: partitionSize
            value: 20000
          - parameterName: chunkSize
            value: 2500
    Tuning-parameters-for-a-document-and-relationship:
      description: Simplified tuning parameters object, showing the updating of both
        a document type's tuning parameters and a relationship's tuning parameters.
        GLOBAL_DOCUMENT and not GLOBAL_RELATIONSHIP, GLOBAL_TRANSACTION shown for
        simplicity.
      value:
        name: partitionTuningParameters
        count: 2
        accept: application/vnd.sas.fcs.svi-indexer.tuning.partition
        version: 2
        items:
        - objectType: GLOBAL_DOCUMENT
          objectName: GLOBAL_DOCUMENT
          parameters:
          - parameter: partitionMultiplier
            value: 1
          - parameter: partitionSize
            value: 2000
          - parameter: chunkSize
            value: 50000
          version: '1'
        - objectType: DOCUMENT
          objectName: intel_report
          parameters:
          - parameter: partitionMultiplier
            value: 1.5
          - parameter: partitionSize
            value: 10000
          - parameter: chunkSize
            value: 10000
          version: '1'
        - objectType: RELATIONSHIP
          objectName: intel_report__person
          parameters:
          - parameter: partitionMultiplier
            value: 1.2
          - parameter: partitionSize
            value: 10000
          - parameter: chunkSize
            value: 10000
          version: '1'
        links:
        - href: /svi-indexer/tuning/partitions
          method: GET
          rel: self
          uri: /tuning/partitions
          type: application/vnd.sas.collection
          itemType: application/vnd.sas.fcs.svi-indexer.tuning.partition
        - href: /svi-indexer/tuning/partitions
          method: PUT
          rel: update
          uri: /tuning/partitions
          type: application/vnd.sas.collection
          itemType: application/vnd.sas.fcs.svi-indexer.tuning.partition
          responseType: application/vnd.sas.collection
          responseItemType: application/vnd.sas.investigation.indexing.tuning.partition
    Object-metadata-for-entities-and-relationships:
      description: An example of a metadata response.
      value:
        entities:
        - qualifiedName: tdc_customer
          label: Insurance Customer
          queryColumns: '"id"'
          tableSize: 10000
          dedicatedSearchIndex: true
          tableName: tdc_customer
          schemaName: finance
        - qualifiedName: individual_customers
          label: Individual Customers
          queryColumns: '"customer_id_number"'
          tableSize: 4993
          dedicatedSearchIndex: true
          tableName: individual_customers
          schemaName: finance
          childObjects:
          - qualifiedName: individual_details_address
            label: individual_details_address
            queryColumns: customer_id_number
            tableSize: 4982
            dedicatedSearchIndex: true
            tableName: individual_details_address
            schemaName: finance
          - qualifiedName: individual_details_telephe
            label: individual_details_telephone
            queryColumns: customer_id_number
            tableSize: 4817
            dedicatedSearchIndex: true
            tableName: individual_details_telephone
            schemaName: finance
          - qualifiedName: individual_details_email
            label: individual_details_email
            queryColumns: customer_id_number
            tableSize: 3979
            dedicatedSearchIndex: true
            tableName: individual_details_email
            schemaName: finance
        - qualifiedName: business_customers
          label: Business Customers
          queryColumns: '"customer_id_number"'
          tableSize: 4843
          dedicatedSearchIndex: true
          tableName: business_customers
          schemaName: finance
          childObjects:
          - qualifiedName: business_details_address
            label: business_details_address
            queryColumns: customer_id_number
            tableSize: 4839
            dedicatedSearchIndex: true
            tableName: business_details_address
            schemaName: finance
          - qualifiedName: business_details_telephone
            label: business_details_telephone
            queryColumns: customer_id_number
            tableSize: 4688
            dedicatedSearchIndex: true
            tableName: business_details_telephone
            schemaName: finance
          - qualifiedName: business_details_email
            label: business_details_email
            queryColumns: customer_id_number
            tableSize: 3878
            dedicatedSearchIndex: true
            tableName: business_details_email
            schemaName: finance
        - qualifiedName: business_account
          label: Business Account
          queryColumns: '"primary_account_number"'
          tableSize: 4090
          dedicatedSearchIndex: true
          tableName: business_account
          schemaName: finance
        - qualifiedName: individual_account
          label: Individual Account
          queryColumns: '"primary_account_number"'
          tableSize: 3943
          dedicatedSearchIndex: true
          tableName: individual_account
          schemaName: finance
        relationships:
        - qualifiedName: individual_customers__accounts
          label: Accounts
          queryColumns: '"customer_id_number","primary_account_number"'
          tableSize: 5180
          dedicatedSearchIndex: false
          tableName: individual_accounts_customers
          schemaName: finance
        - qualifiedName: business_customers__accounts
          label: Accounts
          queryColumns: '"customer_id_number","primary_account_number"'
          tableSize: 5000
          dedicatedSearchIndex: false
          tableName: business_accounts_customers
          schemaName: finance
        transactions: []
    indexRequest:
      description: A sample request to index specific objects.
      x-sas-internal: true
      value:
        documents:
        - type: intel_report
          index:
          - c9385695-95bd-4255-84f6-89de88ea0a3a
          - b7b62a73-2721-4794-8bd7-48e1f8920ef2
          - bc94bdfd-0846-4f52-a41f-97a575931aa8
          delete:
          - f7ecc11d-9783-4aea-ad14-3c8596a2170c
        - type: person
          index:
          - 809a995e-d831-4691-8154-4301ae17f13e
        - type: police_report
          index:
          - 5ab7e1c9-7ec3-404b-b7f5-7c52f10328a8
        relationships:
        - relationshipName: witness
          fromObjectName: intel_report
          toObjectName: person
          index:
          - witness|_|intel_report|_|person|_|bf64709b-e6b9-4aea-8f7e-908ec5ce4ca7
          - witness|_|intel_report|_|person|_|289268e9-3ebf-4ce7-8ced-830991eaec92
          delete:
          - witness|_|intel_report|_|person|_|a086caf5-68cb-4b8f-9943-591e19928a64
        transactions:
        - transactionName: fund_transfer
          index:
          - c9385695-95bd-4255-84f6-89de88ea0a3a-_-bc94bdfd-0846-4f52-a41f-97a575931aa8
          - a086caf5-68cb-4b8f-9943-591e19928a64-_-bf64709b-e6b9-4aea-8f7e-908ec5ce4ca7
          delete:
          - f7ecc11d-9783-4aea-ad14-3c8596a2170c-_-809a995e-d831-4691-8154-4301ae17f13e
    indexRequestWithTransactions:
      description: |
        A sample request showcasing the different formats transaction identifiers can take:
        - "fund_transfer" represents a transaction where a single entity type is selected for both the "from" and "to" entities
        - "purchase_order" represents a transaction where "multiple types" is selected for the "from" entity and a single entity type for the "to" entity
        - "invoice_payment" represents a transaction where a single entity type is selected for the "from" entity and "multiple types" is selected for the "to" entity
        - "salary_payment" represents a transaction where "multiple types" is selected for both the "from" and "to" entities
      x-sas-internal: true
      value:
        transactions:
        - transactionName: fund_transfer
          index:
          - c9385695-95bd-4255-84f6-89de88ea0a3a-_-bc94bdfd-0846-4f52-a41f-97a575931aa8
          delete:
          - f7ecc11d-9783-4aea-ad14-3c8596a2170c-_-809a995e-d831-4691-8154-4301ae17f13e
        - transactionName: purchase_order
          index:
          - from_object-_-c9385695-95bd-4255-84f6-89de88ea0a3a-_-bc94bdfd-0846-4f52-a41f-97a575931aa8
          delete:
          - from_different_object-_-f7ecc11d-9783-4aea-ad14-3c8596a2170c-_-5-_-809a995e-d831-4691-8154-4301ae17f13e
        - transactionName: invoice_payment
          index:
          - c9385695-95bd-4255-84f6-89de88ea0a3a-_-to_object-_-bc94bdfd-0846-4f52-a41f-97a575931aa8
          delete:
          - f7ecc11d-9783-4aea-ad14-3c8596a2170c-_-to_different_object-_-809a995e-d831-4691-8154-4301ae17f13e-_-8
        - transactionName: salary_payment
          index:
          - from_object-_-c9385695-95bd-4255-84f6-89de88ea0a3a-_-to_object-_-bc94bdfd-0846-4f52-a41f-97a575931aa8
          delete:
          - from_different_object-_-f7ecc11d-9783-4aea-ad14-3c8596a2170c-_-5-_-to_different_object-_-809a995e-d831-4691-8154-4301ae17f13e-_-9
    indexFormatVersionResponse:
      description: A sample response for the index format version.
      x-sas-internal: true
      value:
        indexFormatVersion: 1
