---
openapi: 3.0.3
info:
  version: "4"
  title: Types
  description: >
    The Object Type Registry API provides basic create, read, update, and
    delete functions on object types.
  termsOfService: "https://www.sas.com/en_us/legal/copyright.html"
  contact:
    name: "SAS Developers"
    email: "devex@sas.com"
    url: "https://developer.sas.com"
tags:
- name: Root
  description: The operations for the root resource.
- name: User
  description: The operations for non-adminstrator user consumption.
- name: Admin
  description: The operations for administrator or service use.
paths:
  /:
    get:
      tags:
      - Root
      summary: Get a list of top-level links
      operationId: root
      description: Returns a list of links to the top-level collections surfaced through
        this API.
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                json:
                  $ref: "#/components/examples/getTypesRootResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                json:
                  $ref: "#/components/examples/getTypesRootResponse"
  /types:
    get:
      tags:
      - User
      summary: Get a list of object types
      operationId: getTypes
      description: >
        Get a list of object types.  The object types returned can be
        filtered, sorted, and paged. The default sort order will be the
        type name.  Alternative sort orders may be by label, mediaType or
        description.  It is also possible to filter on any of these
        fields, using the functions eq, gt, ge, lt, le, or contains.  You
        can also filter by the tags using the contains function. <br><br>
        /types/types?filter=contains(tags, 'searchable') <br> Returned
        items will be of media type application/vnd.sas.content.type.
      parameters:
      - name: start
        in: query
        description: 0-based Offset of first type to return.  Defaults to 0.
        schema:
          type: integer
      - name: limit
        in: query
        description: Maximum number of types to return.  Defaults to 20.
        schema:
          type: integer
      - name: filter
        in: query
        description: "Filter criteria for returned types. See [Filtering in REST APIs](https://developer.sas.com/rest-apis/types-v4/docs/getting-started/usage-notes#filtering)."
        schema:
          type: string
          format: filter-criteria
      - name: sortBy
        in: query
        description: "Sort returned types. See [Sorting in REST APIs](https://developer.sas.com/rest-apis/types-v4/docs/getting-started/usage-notes#sorting)."
        schema:
          type: string
          format: sort-criteria
      - name: If-None-Match
        in: header
        description: ETag value to check if the resource has changed.
        schema:
          type: string
      responses:
        "200":
          description: The request succeeded and matching object types are returned.
          headers:
            Content-Type:
              schema:
                type: string
            ETag:
              description: An identifier for the specific version of the resource
              schema:
                type: string
          content:
            "application/vnd.sas.collection+json":
              schema:
                $ref: "#/components/schemas/typeCollection"
              examples:
                json:
                  $ref: "#/components/examples/getTypesResponse"
            "application/json":
              schema:
                $ref: "#/components/schemas/typeCollection"
              examples:
                json:
                  $ref: "#/components/examples/getTypesResponse"
        "400":
          description: Bad request.
          content:
            "application/vnd.sas.error+json":
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/getTypesErrorResponse"
    patch:
      tags:
      - Admin
      summary: Patch a collection of object types
      operationId: patchTypes
      description: Patch a collection of object types using JsonPatch methodology.
        Supported operations include 'test' and 'remove'.
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: "#/components/schemas/jsonPatchCollection"
            examples:
              json:
                $ref: "#/components/examples/patchTypesBody"
          application/json:
            schema:
              $ref: "#/components/schemas/jsonPatchCollection"
            examples:
              json:
                $ref: "#/components/examples/patchTypesBody"
        description: A jsonPatch object describing the types to be patched.
        required: true
      responses:
        "200":
          description: The request succeeded.
        "400":
          description: The request was invalid.
          headers:
            Content-Type:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/patchBadRequestErrorResponse"
  "/types/{typeName}":
    get:
      tags:
      - User
      summary: Get an Object Type
      operationId: getType
      description: |
        Get a specific object type definitioni by name.
      parameters:
      - name: typeName
        in: path
        description: This is the name of the existing object type.
        required: true
        schema:
          type: string
      - name: If-None-Match
        in: header
        description: ETag value to check if the resource has changed.
        schema:
          type: string
      responses:
        "200":
          description: The request succeeded and matching object type is returned.
          headers:
            ETag:
              description: An tag that identifies this revision of this object.
              schema:
                type: string
          content:
            "application/vnd.sas.content.type+json":
              schema:
                $ref: "#/components/schemas/objectType"
              examples:
                json:
                  $ref: "#/components/examples/getTypeResponse"
            "application/json":
              schema:
                $ref: "#/components/schemas/objectType"
              examples:
                json:
                  $ref: "#/components/examples/getTypeResponse"
        "404":
          description: The request failed. No type with the given name was found.
          content:
            "application/vnd.sas.error+json":
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/typeNotFoundErrorResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/typeNotFoundErrorResponse"
    head:
      tags:
      - User
      summary: Check availability of an Object Type
      operationId: headersForObjectType
      description: |
        Retrieve the headers and check the availability of an Object Type.
      parameters:
      - name: typeName
        in: path
        description: Name of existing object type.
        required: true
        schema:
          type: string
      - name: If-None-Match
        in: header
        description: ETag value to check if the resource has changed.
        schema:
          type: string
      responses:
        "200":
          description: success.  The object type is returned.
          headers:
            Content-Type:
              schema:
                type: string
            ETag:
              description: An identifier for the specific version of the resource
              schema:
                type: string
        "404":
          description: Not Found.  No type with the given name was found.
          headers:
            Content-Type:
              schema:
                type: string
            ETag:
              description: An identifier for the specific version of the resource
              schema:
                type: string
    put:
      tags:
      - Admin
      summary: Create or Update an Object Type
      operationId: updateType
      description: >
        Create or update an object type.  When creating an object type,
        the name and media type are required.  No defaults are provided
        for other fields, they will be returned as null
        values.  Conditional PUT is supported, but not required.  If an
        If-Match header is provided, it must match the current state of
        the type. The Links field in the body will be ignored on input.
        <br>This is an admin-only operation.
      parameters:
      - $ref: "#/components/parameters/typeNameParameter"
      - name: If-Match
        in: header
        description: "The value of the ETag that was returned from a GET or previous\
          \ PUT of this type.  This header is optional, but if provided, this MUST\
          \ match exactly the current value of the etag of the object."
        schema:
          type: string
      requestBody:
        content:
          "application/vnd.sas.content.type+json":
            schema:
              $ref: "#/components/schemas/objectType"
            examples:
              json:
                $ref: "#/components/examples/createTypeBody"
          "application/json":
            schema:
              $ref: "#/components/schemas/objectType"
            examples:
              json:
                $ref: "#/components/examples/createTypeBody"
        description: updated object type.
        required: true
      responses:
        "200":
          description: object type definition updated successfully.
          headers:
            Location:
              description: The URI of the newly created type.
              schema:
                type: string
            ETag:
              description: An tag that identifies this revision of this object.
              schema:
                type: string
          content:
            "application/vnd.sas.content.type+json":
              schema:
                $ref: "#/components/schemas/objectType"
              examples:
                json:
                  $ref: "#/components/examples/createTypeResponse"
            "application/json":
              schema:
                $ref: "#/components/schemas/objectType"
              examples:
                json:
                  $ref: "#/components/examples/createTypeResponse"
        "201":
          description: object type definition created successfully.
          headers:
            Location:
              description: The URI of the newly created type.
              schema:
                type: string
            ETag:
              description: An tag that identifies this revision of this object.
              schema:
                type: string
          content:
            "application/vnd.sas.content.type+json":
              schema:
                $ref: "#/components/schemas/objectType"
              examples:
                json:
                  $ref: "#/components/examples/createTypeResponse"
            "application/json":
              schema:
                $ref: "#/components/schemas/objectType"
              examples:
                json:
                  $ref: "#/components/examples/createTypeResponse"
        "400":
          description: "Bad Request.  The request is not properly formed.  This can\
            \ happen if the type name in the path does not match the type name in\
            \ the body, or if the body is missing required fields."
          content:
            "application/vnd.sas.error+json":
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/badRequestErrorResponse"
            "application/json":
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/badRequestErrorResponse"
        "403":
          description: "Only administrators can create or update types."
          content:
            "application/vnd.sas.error+json":
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/putTypeForbiddenErrorResponse"
            "application/json":
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/putTypeForbiddenErrorResponse"
        "412":
          description: The ETag provided does not match the current version of the
            object.
          content:
            "application/vnd.sas.error+json":
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/preConditionFailedResponse"
            "application/json":
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/preConditionFailedResponse"
    delete:
      tags:
      - Admin
      summary: Delete an Object Type
      operationId: deleteType
      description: Delete an object type.
      parameters:
      - $ref: "#/components/parameters/typeNameParameter"
      responses:
        "204":
          description: The object type was successfully deleted.
        "403":
          description: "Only an administrator can delete an object."
          content:
            "application/vnd.sas.error+json":
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/deleteTypeForbiddenErrorResponse"
            "application/json":
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/deleteTypeForbiddenErrorResponse"
        "404":
          description: The object type does not exist.
          content:
            "application/vnd.sas.error+json":
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/deleteTypeNotFoundErrorResponse"
            "application/json":
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                json:
                  $ref: "#/components/examples/deleteTypeNotFoundErrorResponse"
servers:
- url: http://example.com/types
  description: This is an example base URL.
components:
  parameters:
    typeNameParameter:
      name: typeName
      in: path
      description: This is the name of the existing object type.
      required: true
      schema:
        type: string
      example: annotation
  schemas:
    objectType:
      description: The object type.
      required:
      - name
      properties:
        version:
          type: integer
          description: "This media type's schema version number. This representation\
            \ is version 3."
          example: 3
        name:
          type: string
          description: >
            Object type name.  This must be unique. The name may be
            divided into up to three segments, separated by an
            underscore ('_'). The first segment is the main type
            name. There should be a type definition with only this
            name. The second segment provides more specific
            information as to what is contained in the object. The
            third segment is an application name that specifies what
            application this resource was created by or is targeted
            toward. As an example, the type definition name
            'file_docx_sasstudio' would be a subtype of 'file' (there
            should be a type with that name), that contains a word
            document, and was created by or is intended for use by
            SAS Studio.
          example: testtype
        label:
          title: Human readable label.
          type: string
          description: A localizable label suitable for presentation to a human.
          example: Test Type
        pluralLabel:
          title: Pluralized human readable label.
          type: string
          description: A pluralized label suitable for humans.
          example: Test Types
        mediaType:
          title: Primary media type.
          type: string
          description: The primary media type string.
          example: "application/vnd.sas.test+json"
        description:
          title: Object type description.
          type: string
          description: The object type description.
          example: "This is a type for testing."
        iconUri:
          title: The URI for the icon location.
          type: string
          description: The URI for the icon location.
          example: "/test/static/icon"
        resourceUri:
          title: The URI for the resource root.
          type: string
          description: The URI for the resource root
          example: "/testTypes/"
        serviceRootUri:
          title: The URI for the service root.
          type: string
          description: The URI for the service root
          example: "/testTypes/"
        tags:
          title: Tags.
          type: array
          description: An array of strings that indicate capabilities or features
            of the type.
          items:
            type: string
            example: "searchable"
        mappedTypes:
          title: Type names that map to this type.
          type: array
          description: An array of strings that represent type names that map to this
            type.
          items:
            type: string
            example: TestType
        properties:
          type: object
          description: "Key/value pairs that describe properties, abilities or characteristics\
            \ of the type or its supporting service."
          additionalProperties:
            type: string
            example: ""
        mediaTypes:
          type: array
          description: >
            Alternate media types for this type definition. This
            field should include the primary media type to facilitate
            searching for type definitions.
          items:
            type: string
            example: "text/plain"
        extensions:
          type: array
          description: >
            An array of strings that represent acceptable file
            extensions for this type.
          items:
            type: string
            example: "txt"
        links:
          type: array
          description: Paging links that apply to this object
          items:
            $ref: "#/components/schemas/link"
    jsonPatch:
      title: A JsonPatch object.
      description: A JsonPatch object containing the path of the item to patch.
      required:
      - op
      - path
      properties:
        op:
          type: string
          description: Operation name. 'test' and 'remove' are the only supported
            operations.
        path:
          type: string
          description: The id of resource to patch.
    jsonPatchCollection:
      title: JsonPatch collection
      description: A collection of resources to patch. Supported operations include
        'test' and 'remove'.
      type: array
      items:
        $ref: "#/components/schemas/jsonPatch"
      example:
      - op: remove
        path: /0b7eeceb-792d-46df-a0af-207b3c794c99
      - op: remove
        path: /b0e25d55-7c2c-4c5e-801f-cec887fbaa2d
    api:
      title: API
      description: The list of links to top-level resources and operations available
        from the root of the API.
      required:
      - version
      - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version
            1.
        links:
          type: array
          description: The API"s top-level links.
          items:
            $ref: "#/components/schemas/link"
    link:
      title: Link
      description: A link to a related operation or resource.
      required:
      - rel
      properties:
        method:
          type: string
          description: The HTTP method to invoke this endpoint.
        rel:
          type: string
          description: The relationship of this URL to the object.
        uri:
          type: string
          description: The relative URI of the REST endpoint.
        href:
          type: string
          description: The full URL of the REST endpoint.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type consumed/produced.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type
            or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`,
            `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body
            for a `PUT`, `POST`, or `PATCH` operation.
    baseCollection:
      description: This is a base schema used to define paginated collections of resources.
        This base schema is extended by other schemas in APIs by adding an 'items'
        array property. These extensions define the application/vnd.sas.collection
        media type (version 2)
      properties:
        name:
          type: string
          description: The name of the collection.
        start:
          type: integer
          description: The zero-based index of the first item in the collection.
        limit:
          type: integer
          description: The number of items that were requested for the collection.
        count:
          type: integer
          description: If populated indicates the number of items in the collection.
          format: int64
        accept:
          type: string
          description: A space-delimited list of media types from which an `Accept`
            header may be constructed.
        links:
          type: array
          description: The links that apply to the collection.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the collection representation. This representation
            is version 2.
    typeCollection:
      title: Collection of Types
      description: This is a collection of object types.
      allOf:
      - $ref: "#/components/schemas/baseCollection"
      - type: object
        properties:
          items:
            type: array
            description: The actual results of a query
            items:
              $ref: "#/components/schemas/objectType"
    errorResponse:
      title: Error
      description: The representation of an error.
      required:
      - httpStatusCode
      - version
      properties:
        message:
          type: string
          description: The error message.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of
            the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred
          items:
            $ref: "#/components/schemas/errorResponse"
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the error representation. This representation
            is version 2.
  examples:
    getTypesRootResponse:
      summary: Types service endpoints
      description: List of endpoints for types service
      value: {"links": [{"method": "GET", "rel": "types", "href": "/types/types",
            "uri": "/types/types", "type": "application/vnd.sas.collection", "itemType": "application/vnd.sas.content.type"},
          {"method": "PUT", "rel": "createType", "href": "/types/types", "uri": "/types/types",
            "type": "application/vnd.sas.content.type"}, {"method": "PATCH", "rel": "patchTypes",
            "href": "/types/types", "uri": "/types/types", "type": "application/json-patch+json"}],
        "version": 4}
    getTypesResponse:
      summary: List registered object types
      description: This endpoint list the registered object types
      value: {"name": "types", "start": 0, "version": 2, "limit": 20, "links": [{
            "method": "GET", "rel": "collection", "href": "/types/types", "uri": "/types/types",
            "type": "application/vnd.sas.collection", "itemType": "application/vnd.sas.content.type"},
          {"method": "GET", "rel": "next", "href": "/types/types?start=20&limit=20",
            "uri": "/types/types?start=20&limit=20", "type": "application/vnd.sas.collection",
            "itemType": "application/vnd.sas.content.type"}, {"method": "GET", "rel": "self",
            "href": "/types/types?start=0&limit=20", "uri": "/types/types?start=0&limit=20",
            "type": "application/vnd.sas.collection", "itemType": "application/vnd.sas.content.type"}],
        "items": [{"description": "A visual representation of the sequence of steps\
              \ and tasks needed to perform a process.", "extensions": ["flw"], "label": "Studio\
              \ flow", "links": [{"method": "GET", "rel": "self", "href": "/types/types/dataFlow",
                "uri": "/types/types/dataFlow", "type": "application/vnd.sas.content.type"},
              {"method": "PUT", "rel": "update", "href": "/types/types/dataFlow",
                "uri": "/types/types/dataFlow", "type": "application/vnd.sas.content.type"},
              {"method": "DELETE", "rel": "delete", "href": "/types/types/dataFlow",
                "uri": "/types/types/dataFlow"}], "mediaType": "application/vnd.sas.data.flow",
            "name": "dataFlow", "resourceUri": "/dataFlows/dataFlows", "serviceRootUri": "/dataFlows/",
            "tags": ["indexable", "parenting", "summary", "catalog"], "version": 3},
          {"description": "Virtual container object", "iconUri": "/folders/icons/folder.png",
            "label": "Folder", "links": [{"method": "GET", "rel": "self", "href": "/types/types/folder",
                "uri": "/types/types/folder", "type": "application/vnd.sas.content.type"},
              {"method": "PUT", "rel": "update", "href": "/types/types/folder", "uri": "/types/types/folder",
                "type": "application/vnd.sas.content.type"}, {"method": "DELETE",
                "rel": "delete", "href": "/types/types/folder", "uri": "/types/types/folder"}],
            "mappedTypes": ["Folder"], "mediaType": "application/vnd.sas.content.folder+json",
            "name": "folder", "resourceUri": "/folders/folders", "serviceRootUri": "/folders/",
            "tags": ["indexable", "parenting", "summary"], "version": 3}, {"description": "A\
              \ vertical component of a table representing physical metadata backed\
              \ by data stored in SAS.", "label": "SAS column", "links": [{"method": "GET",
                "rel": "self", "href": "/types/types/sasColumn", "uri": "/types/types/sasColumn",
                "type": "application/vnd.sas.content.type"}, {"method": "PUT", "rel": "update",
                "href": "/types/types/sasColumn", "uri": "/types/types/sasColumn",
                "type": "application/vnd.sas.content.type"}, {"method": "DELETE",
                "rel": "delete", "href": "/types/types/sasColumn", "uri": "/types/types/sasColumn"}],
            "mediaType": "application/vnd.sas.data.column", "name": "sasColumn", "resourceUri": "/dataTables/dataSources",
            "serviceRootUri": "/dataTables/", "version": 3}, {"description": "A vertical\
              \ component of an in-memory table in SAS Cloud Analytic Services.",
            "label": "CAS column", "links": [{"method": "GET", "rel": "self", "href": "/types/types/casColumn",
                "uri": "/types/types/casColumn", "type": "application/vnd.sas.content.type"},
              {"method": "PUT", "rel": "update", "href": "/types/types/casColumn",
                "uri": "/types/types/casColumn", "type": "application/vnd.sas.content.type"},
              {"method": "DELETE", "rel": "delete", "href": "/types/types/casColumn",
                "uri": "/types/types/casColumn"}], "mediaType": "application/vnd.sas.data.column",
            "name": "casColumn", "resourceUri": "/dataTables/dataSources", "serviceRootUri": "/dataTables/",
            "version": 3}, {"description": "A two-dimensional representation of data\
              \ in SAS, in which the data values are arranged in rows and columns.",
            "label": "SAS table", "links": [{"method": "GET", "rel": "self", "href": "/types/types/sasTable",
                "uri": "/types/types/sasTable", "type": "application/vnd.sas.content.type"},
              {"method": "PUT", "rel": "update", "href": "/types/types/sasTable",
                "uri": "/types/types/sasTable", "type": "application/vnd.sas.content.type"},
              {"method": "DELETE", "rel": "delete", "href": "/types/types/sasTable",
                "uri": "/types/types/sasTable"}], "mediaType": "application/vnd.sas.data.table",
            "name": "sasTable", "resourceUri": "/dataTables/dataSources", "serviceRootUri": "/dataTables/",
            "version": 3}]}
    createTypeBody:
      summary: Body to create an object type
      description: Sample body used to create an object type via PUT.
      value:
        name: testtype
        description: type for testing
        iconUri: "/test/static/icon"
        contextUri: "/test/tests"
        pluralLabel: "testing types"
        mappedTypes:
        - v9test
        - viyatest
        tags:
        - searchable
    createTypeResponse:
      summary: Response to PUT to create an object type.
      description: Here is an example of using the PUT request to create an object
        type.
      value:
        name: testtype
        mediaTypes: []
        extensions: []
        description: type for testing
        iconUri: "/test/static/icon"
        tags:
        - searchable
        pluralLabel: "testing types"
        mappedTypes:
        - v9test
        - viyatest
        properties: {}
        links:
        - method: GET
          rel: self
          href: "/types/types/testtype"
          uri: "/types/types/testtype"
          type: application/vnd.sas.content.type
        - method: PUT
          rel: update
          href: "/types/types/testtype"
          uri: "/types/types/testtype"
          type: application/vnd.sas.content.type
        - method: DELETE
          rel: delete
          href: "/types/types/testtype"
          uri: "/types/types/testtype"
        version: 3
    getTypeResponse:
      summary: Response to GET to retrieve an object type.
      description: Here is an example of using the GET request to retrieve a specific
        object type.
      value:
        name: testtype
        mediaTypes:
        - text/plain
        - application/octet-stream
        extensions:
        - tst
        description: type for testing
        iconUri: "/test/static/icon"
        tags:
        - searchable
        properties:
          content.standalone: "true"
          ttype: ui
        links:
        - method: GET
          rel: self
          href: "/types/types/testtype"
          uri: "/types/types/testtype"
          type: application/vnd.sas.content.type
        - method: PUT
          rel: update
          href: "/types/types/testtype"
          uri: "/types/types/testtype"
          type: application/vnd.sas.content.type
        - method: DELETE
          rel: delete
          href: "/types/types/testtype"
          uri: "/types/types/testtype"
        version: 1
    typeNotFoundErrorResponse:
      summary: Type not found error response
      description: Here is an example of an error response when object type not found
        on GET request.
      value:
        errorCode: 11504
        message: No object type with the name "testtypexxxx" was found.
        details:
        - "traceId: 5da644e2b5844ca0"
        - "path: /types/types/testtype"
        links: []
        version: 2
        httpStatusCode: 404
    badRequestErrorResponse:
      summary: Bad request error response
      description: Here is an example of a bad request error response on a PUT request
        to create an object type. In this example the body did not include a name
        for the object type.
      value:
        errorCode: 1177
        message: The objectType was not valid.
        details:
        - "traceId: 4d148b871720c018"
        - "path: /types/types/testtype"
        - "FieldError: name: Must not be null."
        links: []
        version: 2
        httpStatusCode: 400
    preConditionFailedResponse:
      summary: Precondition failed error response
      description: Here is an example of an error response when PUT request precondition
        fails.
      value:
        errorCode: 11503
        message: The object type has been updated since you last retrieved it.
        details:
        - "traceId: 1277f7c486ad9ad2"
        - "path: /types/types/testtype"
        links: []
        version: 2
        httpStatusCode: 412
    getTypesErrorResponse:
      summary: Get types error response
      description: Here is an example of an error response when GET types request
        specified with invalid filter.
      value:
        details:
        - Bad Request
        - "path: /types/types"
        - "correlator: 32ec17ec-9dd6-4b29-837e-8bef64c28fd1"
        httpStatusCode: 400
        message: Bad Request
        version: 2
    deleteTypeForbiddenErrorResponse:
      summary: Delete type error response
      description: Here is an example of an error response when DELETE specified by
        a non-administrator.
      value:
        version: 2
        httpStatusCode: 403
        message: Forbidden
        details:
        - Unauthorized
        - "path: /types/types/conversationalDomain"
        - "correlator: 49b49e4c-1786-4457-8e49-7faf719ee4ff"
    deleteTypeNotFoundErrorResponse:
      summary: Delete type not found error response
      description: Here is an example of an error response when type not found on
        DELETE request.
      value:
        version: 2
        httpStatusCode: 404
        errorCode: 11504
        message: No object type "testTypeName" was found.
        details:
        - conversationalDomainxx
        - "path: /types/types/testTypeName"
        - "correlator: 772b1e73-b756-474e-a2ae-41e95aaef535"
    putTypeForbiddenErrorResponse:
      summary: Create or update type error response
      description: Here is an example of an error response when PUT specified by a
        non-administrator.
      value:
        version: 2
        httpStatusCode: 403
        message: Forbidden
        details:
        - Unauthorized
        - "path: /types/types/conversationalDomain"
        - "correlator: 49b49e4c-1786-4457-8e49-7faf719ee4ff"
    patchTypesBody:
      summary: Body to patch types
      description: Sample body uses PATCH request to test if type exists and if so
        deletes.
      value:
      - op: test
        path: "/types/types/testType"
        value:
          name: testType
      - op: remove
        path: "/types/types/testType"
    patchBadRequestErrorResponse:
      summary: Patch types error response
      description: Here is an example of an error response when PATCH request contains
        invalid operation. Only 'test' and 'remove' are supported.
      value:
        version: 2
        httpStatusCode: 400
        message: Bad Request
        details:
        - "Unsupported patch operation: add"
        - "path: /types/types"
        - "correlator: 92f71781-6a61-421c-843c-b08f03048c34"


